### ISSUE TITLE
Research BIP Kafka events to support product metrics tracking

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1196]
**User Story**

As a member of the HTN team, I want to know if there are BIP Kafka events that VRO could subscribe to that would enable us to measure certain product metrics.

**Acceptance Criteria**

1. Review the [catalog of events](https://community.max.gov/pages/viewpage.action?spaceKey=VAExternal&title=Benefits+Integration+Events)
2. Note the events that might VRO might want to subscribe to to help us measure our [product metrics](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1670355940781/0657c82ab2274d7763a185e1bd95865ea933f0d1?wid=0-1675811191147) and any other considerations
3. Update [spreadsheet](https://docs.google.com/spreadsheets/d/1bjFyMVk56nfbTVUtCFQMoq2-Ri2ui_pQnvK8L9Xsh7s/edit?usp=sharing) to track what data points we have identified from which sources (Amy) 

**Potential use cases, written in the form of a question**
- Could we use `contention closed dates` as a way to measure the # of days it takes to process a particular contention? Might be helpful information when we start processing multi-issue claims.
- Are there events related to when a `claim is assigned to an RVSR`, `when a rating decision is made`, and/or `when the claim is closed`? so we can measure the # of days it takes for a claim to get through the different stages of the claims process and get a better sense for which phases are taking a long time.
- Are there events related to `rating decisions` (e.g., grant, denial) and/or `ratings` (e.g., 10%) to track the outcome of certain claims? (note: I think the [LH Veterans Verification API](https://dsva.slack.com/archives/C031RRFCHV1/p1668721458382549?thread_ts=1668708810.870479&cid=C031RRFCHV1) might have some of this info too)
- Are there events related to `exam ordering` so we can track when a RVSR manually orders an exam for a claim? or when the exam results are received?
- Would we be able to get information about a Veteran's `current rating` so we can compare the new rating with the previous?

**Notes about work**

Difference between BIP/BIA/BIE: https://dsva.slack.com/archives/C04QLHM9LR0/p1677695647037709

> BIPlatform = environment where Kafka events flow
> BIArchitecture and Solutions = team that manages BIP
> BIEvents = catalog of events

For context on using the event stream integration, we're (VRO) currently talking with BIA about targeting a June timeline

**Comment by nanotone** [comment]
I'll leave my investigation notes here, since there are a bunch of useful Kafka events and they don't all correspond neatly to metrics in the spreadsheet.

Claim Events
- **ClaimLifecycleStatusUpdatedEvent** - Lifecycle status changed. There are a bunch of data fields here, and seeing this event "in the wild" may be the best way to learn about many of them. Two that jump out at me are `ActorStation` and `ActionUserId`; these presumably refer to the VBMS user who enacted the lifecycle status update, and we might be able to query what kind of user they are (e.g. VSR vs RVSR)
- **ClaimClosedEvent** - This should be the last thing that happens to a claim. I don't know if there's anything particularly meaningful about this that wouldn't be captured by a lifecycle status update, but it could help surface any edge cases of claims that might otherwise fall through the cracks.
- **ClaimUpdatedEvent** - Seems like a catch-all for anything that changes with a claim. Likely to be extremely firehose-y, but potentially someplace to look if we're not sure where else to find certain data.

Contention Events
- **ContentionCompletedEvent** - raised when a contention has been completed. I assume this means that the contention processing is done, which would be useful for multi-issue claims.
- **ExamOrderedForContentionEvent** - raised when an exam is ordered for a contention. Seems pretty straightforward, but see the next section for exam-specific events.

Exam Events
- **ExamRequestedEvent** - An examination has been requested. The data model should specify the type of exam being requested and/or category of exam (Fiduciary, Medical, Veteran Status, etc.)
- **ExamCompletedEvent** - The exam has been completed successfully.
- **ExamResultsAvailableEvent** - The results of the examination have been uploaded/stored with the appropriate authority of source.

Ratings Events
- **RatingProfileCreatedEvent**, **RatingProfileUpdatedEvent** - these are basic CRUD operations on rating profiles, and may not correspond to meaningful events for us, although they should always happen if the Veteran gets a new rating.
- **RatingFinalizedEvent** - occurs when the RVSR clicks on the finalize button in VBMS-R. Note - any approvals needed would be done prior to the finalize button. My understanding is that this is the last step in rendering the decision, before things hop over to VBMS-A (awards).
- Commentary: one strategy might be to listen for these events, but use them primarily as a trigger to query BGS (or whichever modern API from LH or BIP provides parity) for the actual new rating data if that's what we care about. Note also that if the decision is a denial, nothing happens in ratings land.

**Comment by amylai-nava** [comment]
@dianagriffin meant to [cc you on this](https://github.com/department-of-veterans-affairs/abd-vro/issues/1196#issuecomment-1472577766) as a FYI since I think Luke was also looking into BIP Kafka events?

**Comment by dianagriffin** [comment]
@amylai-nava Thank you! Good timing -- Luke just completed successfully connectivity testing in DEV8 on the Contention events over in #1159

**Comment by dianagriffin** [comment]
@amylai-nava cc/ @nanotone on a call with CC team about their potential metrics tracking needs and Luke pointed out that some of the events [listed above](https://github.com/department-of-veterans-affairs/abd-vro/issues/1196#issuecomment-1472577766) appear to not yet be available in production (based on "draft" state noted in the [documentation](https://community.max.gov/pages/viewpage.action?spaceKey=VAExternal&title=Benefits+Integration+Events)). 

To take the next step on this (whenever we're ready) we should pin down a list of which events we would want to start subscribing to for our metrics measurement, and then we can go to the BIE team to get the status/current plan for any of those events that are not yet live -- and potentially influence their prioritization of it.

**Comment by yurenanava** [comment]
Thanks for sharing. Super helpful information for our team
