### ISSUE TITLE
vets-api <> BGS investigation around adding notes in VBMS

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1277]
**User story**
As a VA PO, I want to know whether we can **query** BGS via vets-api to return notes that are entered in VBMS and whether we can **add** notes in a lower environment. If so, we'll work on getting this functionality into VRO.

**Context**
- One thing coming out the iMVP gap analysis that we will likely need to address is that MAS is adding data to the notes field on the claim in VBMS, which are used by PA&I for metrics tracking and by RVSRs to understand whether automation has completed for a claim
- We may need to figure out how VRO can add the same notes so that the metrics remain consistent
- Premal poked around at the BGS documentation and said it looks like BGS has functionality to add notes
- Premal suggested that we could use the vets-api connection with BGS to confirm that it has the functionality we need — find some claims we know have notes and then query BGS via vets-api to see if it returns those same notes, then maybe test adding notes via BGS in a lower environment
- If we can confirm that BGS has the functionality, then Premal can work on getting a VRO<>BGS connection set up

**Comment by amylai-nava** [comment]
@dianagriffin here's the ticket we talked about. @nanotone fyi, we may need your help with this one!

**Comment by va-albers** [comment]
BGS API reference [here](https://community.max.gov/pages/viewpage.action?pageId=2212129431)

A possible service match?
**DevelopmentNotesService**
MAP-D Web Service – Not on UDDI yet

**Service Description**
This service allows the Development Notes to be created, edited and deleted. This service uses the following tuxedo services: CCDNOTE, DCDNOTE, XCDRDNOTES, UCDNOTE

Methods
•	createNote - This method is used to create Claim Development notes in the Corporate database
•	createNotes – This method is used to create multiple Claim Development notes in the Corporate database.
•	deleteNote - This method is used to delete Claim Development notes in the Corporate database.
•	findDevelopmentNotes - This method is used to find Claim Development notes in the Corporate database.
•	updateNote - This method is used to update a Claim Development note in the Corporate database.
•	readDevelopmentNotesByVetPtcpntId

WSDL
http://bepdev.vba.va.gov/DevelopmentNotesService/DevelopmentNotesService?wsdl

**Comment by nanotone** [comment]
Yeah, that looks like the one. `bgs-ext`, the Ruby gem that vets-api uses, has [this client implementation](https://github.com/department-of-veterans-affairs/bgs-ext/blob/master/lib/bgs/services/development_notes.rb), which supports only `find_development_notes_by_pid` and `create_note` functions; the former should be sufficient to test out in vets-api prod.

**Comment by nanotone** [comment]
I confirmed that vets-api's BGS client has working access use `find_development_notes_by_pid`, via the following Rails console session in prod:

```ruby
# first, pick a recent Form526 submission ID from #rrd-to-mas-all-claims
f526 = Form526Submission.find(form_sub_id)
user = User.find(f526.user_uuid)
bgs = BGS::Services.new(external_uid: user.icn, external_key: user.common_name)
notes = bgs.notes.find_by_development_notes_by_pid(user.participant_id)
notes[:notes].count
# => 29 returned for this veteran
notes[:notes].map { |n| n[:txt] }
# => yep, those look like notes
```

Note that this only works for recent Form526 submissions, because the necessary user credentials are stored temporarily in Redis (as per the `User.find` call), not permanently in the vets-api SQL database.

I have not tested the other endpoint, `create_note`, since that would write to BGS in prod, but did want to point out that other parts of the vets-api codebase do appear to be using this endpoint:
- [Form686c](https://github.com/department-of-veterans-affairs/vets-api/blob/038d59e/app/workers/bgs/submit_form686c_job.rb#L21) adds a note [Claim set to manual by VA.gov: This application needs manual review...](https://github.com/department-of-veterans-affairs/vets-api/blob/d5e5731/lib/bgs/form686c.rb#L186-L187) for various reasons specified in the code.
- Similarly, [Form674](https://github.com/department-of-veterans-affairs/vets-api/blob/038d59e/app/workers/bgs/submit_form674_job.rb#L21) currently always adds a note [Claim set to manual by VA.gov: This application needs manual review...](https://github.com/department-of-veterans-affairs/vets-api/blob/37eaa11/lib/bgs/form674.rb#L51-L55)
