### ISSUE TITLE
Next steps for BIP Kafka events for RRD metrics

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1410]
Link to previous research on BIP Kafka events that could be used to support product metrics: https://github.com/department-of-veterans-affairs/abd-vro/issues/1196#issuecomment-1472577766

See if we can solve #1408 with kafka events rather than polling the Claims API

**Comment by dianagriffin** [comment]
3 purposes:
1. CC team using contention classification events as part of their model
2. RRD metrics
3. long-term, replacing MAS as the source of VRO being notified about claims to automate

**Comment by yoomlam** [comment]
OBE

**Comment by pshahVA** [comment]
@dianagriffin we may revisit at part of VRO evolution.

**Comment by dianagriffin** [comment]
@pshahVA yes, definitely think we can/should/will continue work against the BIP kafka events as part of VRO. I closed this specific ticket since it was a placeholder specific to exploring Kafka events for RRD metrics, with the assumption that we will spin up new tickets to represent VRO focused efforts and next steps.

**Comment by dianagriffin** [comment]
@pshahVA For VRO metrics/efforts we should also consider Event Bus as an alternative to BIP kafka streams -- I have an item on my to-do list to set a follow-up time with us and Karen to discuss that option further.
