### ISSUE TITLE
Define a VRO release process by creating a more official VRO X.0.0 release

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1498]
**User Story**

As a VRO engineer, I want to pair with my teammates on going through the process of defining the release creation process by creating a 2.0.0 release, so that we have a defined process for creating releases going forward and have a release that represents iMVP.

**Acceptance Criteria**

1. Schedule a working session with VRO engineers & Diana to discuss & define the process of creating a release. 
2. Document the process
3. Draft release notes for 2.0.0
4. Codebase is in a recognizable state of being officially 2.0.0 (tagging)
5. 2.0.0 codebase is running in production environment
6. Any team member can do a release following completion of this ticket

**Not included in this work**
The release process described in this ticket covers the way that new features or changes are made to the VRO platform and its offerings to partner teams or platform users. It does not cover the process by which partner teams or platform users deploy/release changes to their own logic or use cases.

**Notes about work**
- [Relevant slack thread](https://dsva.slack.com/archives/C04QLHM9LR0/p1682097969161719?thread_ts=1682093095.949039&cid=C04QLHM9LR0)

**Comment by yoomlam** [comment]
- [Deploying VRO](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO)
- [Quick Deploy Instructions](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Quick-Deploy-Instructions)

**Comment by dianagriffin** [comment]
Should it be Version 2.0 or Version 3.0??

**Comment by msnwatson** [comment]
version 2.1?

**Comment by yoomlam** [comment]
Based on [Semantic Versioning](https://semver.org/), I'll withdraw my proposal about `2.1.0`. The version after `2.0.0` (iMVP) that _removes_ the RRD functionality should be something like `3.0.0-prerelease` since:
> MAJOR version [is updated] when you make incompatible API changes

I'm open to discuss. And we probably need some procedure that verifies new VRO version numbers comply with Semantic Versioning.

**Comment by msnwatson** [comment]
[This wiki page](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Release-Process-%5BDRAFT%5D) hosts the definition of the release process.

**Comment by msnwatson** [comment]
The wiki page mentioned above contains the instructions that have come out of this ticket so far. There are a couple of clarifying points to be added about releasing commits that are not the latest on the `develop` branch, where to list tickets relating to SecRel acknowledgements and release notes, and a couple of other minor changes. 

@yoomlam and I paired to create a 2.0.0 release; however, it did not pass SecRel because of some expired acknowledgements and one new library issue. I am working to create a 2.0.1 release which should address these concerns before handing off to @greene858 and @tcraghu to complete a new run through of the release process.

**Comment by msnwatson** [comment]
@greene858 and @tcraghu  you all should be good to go in creating a new release 2.0.1. The caveat being that we should avoid including any commits >= #1548 as this begins the process of getting the code into a release 3.0.0 state.

**Comment by dianagriffin** [comment]
@greene858 and @tcraghu In scrum on Friday we talked about you pairing on this today -- did that happen? My understanding is that you two getting together to walk through the documented process is that last step to complete this ticket, so if you can do that to close out the ticket ahead of sprint planning tomorrow, that would be great. If that's not possible, please let me know what's blocking it so we can discuss in sprint planning.

**Comment by dianagriffin** [comment]
Some steps in the release process need to be rearranged, then @greene858 / @tcraghu will re-attempt running a release.

**Comment by tcraghu** [comment]
@greene858 , I have followed instructions to release.3.0.7. Can you please try executing these steps?
