### ISSUE TITLE
Consolidate domain-rrd code and exclude from VRO builds

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#1509]
Most RRD code has been moved to `domain-rrd`. There still remains RRD code in `app` and `service-python`. They need to be extracted from `app` or moved entirely (`service-python`) to `domain-rrd`.
Also update GH Action workflows to build/run/test VRO without enabling/using RRD code.
- retain end2end-test.yaml but rename to make it obviously RRD; allow it to be run manually, but don't run as part of VRO tests
- assess other workflows and repeat if relevant

Yoom can pair with the assignee to get them started and refine the ticket.

**Comment by msnwatson** [comment]
I have filed several PRs toward this ticket; however, I have faced some difficulties because of some discrepancies in the requirements enforced by different parts of our build and test systems, particularly related to moving the `service-python` directory.

I have also faced some issues with disentangling some of the tests from the `app` subproject relating to the `domain-rrd` code to complete the consolidation.

I am continuing to make progress on these two fronts but the unexpected difficulties have slowed my progress.
