### ISSUE TITLE
Spring Cleaning- Audit documentation included in the VRO wiki

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1530]
**User Story**

As a VRO team member, I want to understand what VRO platform documentation is available in the VRO wiki and who it's targeted towards, so that I can make informed choices about updating the wiki's information architecture for easier navigation.

**Acceptance Criteria**

1. VRO wiki pages have been catalogued and categorized according to their topic, audience, and purpose 
2. If you find RRD pages, archive them because they are not needed 
3. Any open questions resulting from the wiki page audit have been reviewed with the VRO team and answered with team input

**Not included in this work**

- #1528 
- #1529

**Comment by greene858** [comment]
This ticket could benefit from User Research on the effectiveness of the existing documentation. 

Needs discussion by the whole team. 
Need a clearer vision of the audience (public vs. team) for the documentation.  

- Who is the audience of the Wiki? 
- What is the purpose of the Wiki? 
- How will we measure the success of the Wiki?

Iterate!

**Comment by meganhicks** [comment]
Hi Erik- I see wiki is reorganized. Before I say yes to closing this I have a question: 

1.  Did you find anything that you thought we should not have? If so, did you retire any pages? Please document what you retired if you did.  Also, if you updated any pages can you document this as well.

**Comment by nelsestu** [comment]
Significant reorganization of Home.md 
* VRO project summary and purpose sections were added to the home page. The content of these sections was largely pulled from documents in VA sharepoint, and edited for relevancy and accuracy.
* The home page's primary function is to act as an index for the rest of the wiki.  For this index function, additional categorization and groupings of links we added to enhance browsability of the index.  
* Bash scripting was used to ensure that all pages are represented somewhere in the index (previously some pages weren't in the home index).

The GitIgnore file of the repository was updated to allow for the wiki to be hosted as a local obsidian markdown repository. 

References to Apache Camel were removed, including the following:
* Apache-Camel.md - the page itself and incoming links
* Code-structure.md - rewrote the section describing how partner applications interact with VRO services, which was the original intent of camel.

BIP-Claim-Evidence-API.md and other references to the Claims-Evidence API.  
* The claims evidence API was not ported from RRD and while there was no way to invoke it, there were still docs referencing it.  Any documentation that was no longer relevant was removed.
* BIP-Claims-API.md referenced the evidence api in a number of places and was updated to remove these sections

The VRO Console page and related mentions of that RRD platform feature have all been removed.

Removed the architecture decisions section of the wiki since it has not been adopted by the team.
