### ISSUE TITLE
make bip into a standalone service

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#1594]
Make the BIP code extracted by previous story into a microservice compliant with [this specification](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions#service-microservice-container-module).  It should listen a Rabbit MQ channel

ACs:
- update/improve https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claims-API
- `./gradlew :svc-bip-api:dockerComposeUp` starts up images rabbitMQ and `svc-bip-api` as well as `va/abd_vro-app:latest`
- is structured similar to `svc-lighthouse-api` service
- api based on [this](https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/svc-bip-api/src/main/java/gov/va/vro/bip/service/IBipApiService.java) is available via RabbitMQ

**Comment by dianagriffin** [comment]
@greene858 and @engineer-plus-plus Could you please add more detail to this ticket, including acceptance criteria?

**Comment by engineer-plus-plus** [comment]
@dianagriffin , requirements analysis, with will result in acceptance criteria is a part of the ticket.  It this point, I can't state them.  Maybe @greene858 or Yoom can.

**Comment by dianagriffin** [comment]
From[ slack](https://dsva.slack.com/archives/C01AXBZA3QR/p1686077548314679?thread_ts=1686077344.358979&cid=C01AXBZA3QR), 
> The BIP microservice could probably use more tests and maybe documentation

Please include in the ACs

**Comment by dianagriffin** [comment]
@engineer-plus-plus will update ticket description to include user stories and ACs.

**Comment by engineer-plus-plus** [comment]
Here are reqs for integration with the tow BIP services.  
https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claim-Evidence-API
https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIP-Claims-API

**Comment by engineer-plus-plus** [comment]
There is a slew of other issues with the `svc-xample-j`.  I'll start creating issues for them in the git repos.  Here is the [first one](https://github.com/department-of-veterans-affairs/abd-vro/issues/1734)

**Comment by engineer-plus-plus** [comment]
I'm still getting it.  But it's not a blocking problem.

**Comment by engineer-plus-plus** [comment]
When developing the RMQ interface for VRO, I'm running into the following problem. In my implementation, the server returns a different DTO when it encounters a problem. While it makes logical sense to not return an invalid business DTO just to convey the error message, it'll make it really hard for clients to deal with. That's why the example used business DTO to send error message.

But the example only has one possible DTO returned. In bip-api's case, there are several. So the centralized error handling routine should somehow know which DTO to send back. It needs to know the return value of the method that threw the exception.

To solve this, it may be possible to use reflection in the constructor of BipException to save the caller's return type in the BipException object.

However, this solution has its major flaw. What if there is an exception thrown that isn't caught and converted to BipException. For example, when the request's format is invalid to create the DTO of the parameter of the handler, Spring throws and exception before the handler even starts.

Spring does know which handler the message was routed to. Maybe we can look for the method annotated with @RabbitListner in the stack trace. Or maybe we can use message to find out the name of the queue it was sent to. From that, we can determine the name of the function.

**Comment by engineer-plus-plus** [comment]
The problem with the example integration test that Yoom wrote is following. When ran within IntelliJ, server's log is not shown. That's bad.

To fix that, I'm trying following. I will make the test not create the server's instance. Instead the test will rely on the instance alrady running. That way, I can see the logs of the separately-running instance of the server. To do that, remove the @SpringBootTest annotation from the test class and, thus, instantiate RabbitAdmin manually .

**Comment by engineer-plus-plus** [comment]
Well taking the spring boot out of the test didn't work too well.  Had to undo it.  The reason was that something changed and the messages were not converted to DTOs any more.  I was just getting byte arrays and didn't really know what to do with them. It would be too much work to figure it out.  I'll just struggle without logger output from the service for now.

**Comment by engineer-plus-plus** [comment]
One idea that I began to implement to solve the challenge of returning the correct type from the error handler is following.  Use the name of the que of the failed message to determine the name of the returned type.  Then use it to instantiate the returned object.  But the code for that wold be too ugly.  Considering that instantiated object can not be assigned to correct variable type.  I'm going to undo that.

The better solution, I think, is to have a separate error handler for each que  create the returned object.  Then, a superclass can handle reporting the error.  

To keep it cohesive, I'll separate the config, creating separate config class for each que.

**Comment by engineer-plus-plus** [comment]
[Pull request](https://github.com/department-of-veterans-affairs/abd-vro/pull/1774/files) containing a vertical slice of the total solution.  It implements two out of 5 endpoints

**Comment by engineer-plus-plus** [comment]
Current iteration of [pull request](https://github.com/department-of-veterans-affairs/abd-vro/pull/1799/commits).  Hopefully this one will be more popular with the reviewers.
