### ISSUE TITLE
Allow release of commits other than the most recent one

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1599]
**User Story**

As a VRO platform engineer, I want to be able to choose a specific commit to release, so that I have a fine-grained control over the code that is deployed to production.

Right now, our release process only formally supports a release of the latest commit on the `develop` branch. There are some workarounds to this in the short-term, but we need to adapt our process to have this functionality built in to our release process.

**Acceptance Criteria**

1. A VRO engineer trying to deploy to the VRO platform can choose any commit (later than the commit currently released) and successfully complete the release process.
2. VRO engineers have reviewed and approved the process definition

**Not included in this work**
Code changes to support enforcement of a policy or process for this should be completed in a followup ticket.

**Notes about work**
- [Current release process definition](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Release-Process)

**Comment by yoomlam** [comment]
Some options:
1. (easiest) Only tag the commit; don't update the version numbers in the code. Basically skip the `./gradlew release` step. 
   - No coding needed; just update the process documentation to make that step optional.
   - Impact: version numbers in the code (and presented in particular UIs and logs) aren't accurate.
2. Insert new commits in the git history using `git rebase` -- [details](https://stackoverflow.com/questions/4067006/git-usage-inserting-commits-prior-to-head)
   - Requires some git know-how; requires everyone to resync their `develop` branch and any other branch based on the outdated `develop` commit.
   - Version numbers and git commit history are accurate
3. Keep a separate `main` branch so that we can run the `./gradlew release` step on the `main` branch only
   - The `develop` branch will not reflect the release. (If `./gradlew release` is run on the `develop` branch as well (without a `rebase`), the ordering of the release isn't logical b/c the release will be appended after the latest commit.)
   - Must maintain/manage 2 commit histories (for `develop` and `main`). The benefit may not be worth the effort.

Currently, I'm leaning towards incorporating into the process: do option 2; if unable or adds undue complexity, fall back to doing option 1.

**Comment by msnwatson** [comment]
This ticket is being deprioritized at the time of this comment. While this ticket represents a useful functionality for the release of the platform, there is no immediate need for the capability, and any modifications to the release process would need to be carefully considered to avoid disruption of Team CC's launch.

Also during refinement discussion, it became clear that there was some conflation between this ticket and a deployment rollback function. That is, this ticket covers the function of creating a new release from a non-HEAD commit while a separate ticket should be created to cover documenting/creating a deployment rollback.

**Comment by yoomlam** [comment]
Rollback *should* be as simple as specifying the older release tag -- see https://github.com/department-of-veterans-affairs/abd-vro/wiki/Deploying-VRO#deploy-images-with-the-release-tag. If that is all that you're thinking of, documenting this is less than an hour of work (and so doesn't require a ticket).
