### ISSUE TITLE
Solution planning for CFI work

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#1715]
## Definition of Done
* A write up of the proposed technical design & architecture (see context below)
* Tickets to represent the work that we can start in the next sprint

## Context
This ticket describes new feature development for the EE team to support the `reduce confirm & continue decisions on tinnitus claims for increase (CFI)` effort.

### MVP solution
* See [mural diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686611425680/24441fa7cc71e50b4b1dbd9e053693655b4e0b5e?wid=0-1687364231812)

### User stories
* As a EE product owner, I want to know whether a Veteran is service connected to Tinnitus at the highest rating percentage (10%) so that we can inform/educate the Veteran when they are submitting a claim for increase for Tinnitus. 
* As a Veteran that's service connected to Tinnitus, I want to know what my rating is and whether I'm eligible to receive additional benefits based on my current rating.

### High-level requirements
* We can identify Veterans who are service connected for Tinnitus and what their current rating is
* We can identify what the highest rating percentage is for Tinnitus (for MVP, we could store this in VRO)
* When appropriate, we display updated text on the 526 application that informs/educates the Veteran about their rating
* We can identify what happens: Veteran submits CFI or not
* We can apply this solution to other disabilities in the future

### Not included in this work
* Any work for disabilities other than Tinnitus
* We will not be preventing Veterans from submitting CFI, only informing
* Any changes to the claims status tool, since claim status tool is not listing out all conditions on that claim.

**Comment by nanotone** [comment]
The Max CFI project aims to identify veterans who are at the maximum rating for tinnitus, and display appropriate messaging when they attempt to submit a 526 claim for increase for tinnitus. Engineering work will accomplish this by implementing a solution in 3 phases:
- Adding a maximum rating field to the disabilities data structure returned by vets-api
- Storing the maximum rating for tinnitus in VRO
- Updating the 526 frontend to display messaging when appropriate

Each of these phases will be described in detail below. The resulting architecture for all components affected by this effort is shown here:

<img width="432" alt="Screen Shot 2023-06-30 at 17 51 16" src="https://github.com/department-of-veterans-affairs/abd-vro/assets/282869/899e4606-ba39-4b97-9c33-905488d2e41c">

## Phase 1 (VA.gov backend)
No VRO dependency is involved here.
- Update vets-json-schema to include CFR's max rating for each disability returned by `/disability_compensation_form/rated_disabilities` and/or `/disability_compensation_form/rating_info`
  - Note that *all* changes to the frontend/backend data contract require a PR in vets-json-schema.
- Update vets-json-schema dependency in vets-api.
- Include 10% max rating for each tinnitus disability rating returned during the 526 flow.

## Phase 2a (VRO dependency)
Storing maximum ratings in VRO is desired for MVP, but not strictly necessary.
- Create a new API handler in VRO for max CFI.
  - The addition of an API for a new VRO domain, alongside the CC API, may require structural changes to VRO's API gateway. 
- Implement an API endpoint that takes a list of disabilities and returns their max ratings if known. For MVP, the only disability with a "known" max rating is tinnitus.
- Update vets-api to use VRO client to use VRO's max CFI API rather than use local ruby code.
  - This should be put behind a feature flag.

## Phase 2b (VA.gov frontend):
Phase 2b can occur at the same time as 2a. This section is largely TBD, pending design/research results on how best to display max ratings on the frontend.
- Update vets-json-schema dependency in vets-website.
- TBD
