### ISSUE TITLE
Update the Mock Kafka service to include topics, authentication that resembles BIE's auth

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/abd-vro#1823]
**User Story**

As  , I want  , so that  .

**Dependent on** 

**Context**
You will need to:
- Create Kafka topics exactly like BIE's
- Test out existing auth in Mock, evaluate to see if we need to make any adjustments to resemble BIE's auth service using SSL (connectivity is described here - https://github.com/department-of-veterans-affairs/abd-vro/issues/1674)

**Acceptance Criteria**

1. VRO's mock kafka service mimics BIE's kafka topics 

**Notes about work**
- This ticket is part of epic #1642

**Comment by chengjie8** [comment]
Currently we are using binami's image to start kafka broker(cluster). In order to implement the authentication on the broker, we will need to do the followings:
1. Create SSL key and certificate for the broker
2. Create a CA
3. sign all certs in the keystore with the CA from above
4. Configure kafka broker to use SSL in the config property file like this:
 ```
 listeners=PLAINTEXT://:9092,SSL://:9093
ssl.keystore.location=/var/private/ssl/kafka.server.keystore.jks
ssl.keystore.password={keystore-password}
ssl.key.password={key-password}
ssl.truststore.location=/var/private/ssl/kafka.server.truststore.jks
ssl.truststore.password={truststore-password}
```

**Comment by yoomlam** [comment]
This will be completed once #1679 is completed.
