### ISSUE TITLE
Technical Solution Design for Data Visibility

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#1849]
As a VRO Engineer, I want to explore a potential implementation for the Data Visibility Epic so that I can breakdown tasks, assess risks, and clarify requirements.

**Acceptance Criteria**

1. A solution is documented and reviewed by VRO engineers, Cory, and Steve
2. Document lists all major components, their responsibility, their interactions with other components, and their specific technologies
3. Document shows flow of data and any processing, including timing 
4. Document lists risks with solution, including security, dependancy on other teams/resources, current VRO system and team skills.
5. Solution identifies phases, where each phase can be completed and deliver value to the customer.
6. Document links to documents/threads that are essential or dictate aspects of the solution 

**Notes about work**

- This solution will only address the queries listed below. Other requirements can be addressed in additional stories.

_From the VRO Goal Workshop:_ 
Some example questions teams are querying the database for:

For disability benefits claims submitted via the va.gov 526EZ form...
- How many claims have had the contention X, in the last 6 months, through va.gov?
- On average, how many claims for increase are submitted per week?
- How many evidence files on average are submitted for each claim? Has that gone up or down over time?
- How many evidence files do users claiming contention X upload?
- How many pages on average do each evidence file havE?
- Over all-time, what is the most frequently occurring contention?
- How many submissions come from users in Lansing, Michigan?
- What are the unique counts of different error messages received from a certain time-range?

**Comment by dianagriffin** [comment]
For the portion of this exploration related to "How will we get the data?", see @va-albers note ([from Slack](https://dsva.slack.com/archives/C04KW0B46N5/p1690525600951349?thread_ts=1690302121.708509&cid=C04KW0B46N5)):

> [@Carly Jones](https://dsva.slack.com/team/U04EV46DVE3) also did some work on setting up an extract like this - we could look into starting from what she has already created?
> I think this is the branch in question:  https://github.com/department-of-veterans-affairs/vets-api/tree/feature-27-call_cc, particularly [exporter.rb](https://github.com/department-of-veterans-affairs/vets-api/compare/master...feature-27-call_cc#diff-d4920cdcc242a371d41dc0eb04e8eabe2e35d3a86339161813b5341cf8f42fd5) and [submit.rb](https://github.com/department-of-veterans-affairs/vets-api/compare/master...feature-27-call_cc#diff-ee2c54fe9f86027c39ad663befc9508dcb4a2c2234e5f9360c62254ead6abed9) would be a good place to start?

**Comment by dianagriffin** [comment]
See [notes from discussion with DBEx](https://docs.google.com/document/d/1rGV18HQcmzzcS0MGkZb8hXh4RjhAObnpkdJFWFYw2K4/edit#heading=h.va8ut8pnv86m) and ongoing discussion in [#benefits-data-visibility-initiative](https://dsva.slack.com/archives/C05KA24RPMG)

A key point from that discussion is the idea that an overall solution to this epic needs to answer 4 questions: 
1. What data?
2. How do we get the data?
3. Where do we put it?
4. How do we let people access it?

I'd advocate that for this technical design you focus on questions 2 & 3, _How do we get the data & where do we put it?_

For question 1 (_What data?_), as noted in the ticket description, focusing on the data elements needed to answer the example questions provided is sufficient for now -- or even just a subset of those questions, e.g. the ones about counts and frequency of different claim types/contentions. 

For question 4 (_How do we let people access it?_), I think we can punt for now in order to focus on 2 & 3.

**Comment by dianagriffin** [comment]
Links to form 526 schema in this slack post: https://dsva.slack.com/archives/C01AXBZA3QR/p1689714497462379?thread_ts=1689696619.328689&cid=C01AXBZA3QR

**Comment by dianagriffin** [comment]
Also relevant: https://github.com/department-of-veterans-affairs/vets-api/blob/master/db/schema.rb

**Comment by dianagriffin** [comment]
Based on discussion 8/9 (with @pshahVA, @greene858, @tejans24, @dianagriffin, & @CorySohrakoffUSDS):

- We are all on the same page that our starting point for 1) How will we get the data? and 2) Where will we put it? will look something like the following:
   - [va.gov Postgres DB] --> [Sidekiq job] --> [S3 bucket in VRO] --> [RDS database in VRO] 
- **Next step**: @greene858 will diagram/document this and run it by @CorySohrakoffUSDS and @va-albers for input
   - From there, we'll identify the open questions we need to answer & logistical next steps needed to get started
   - We are holding off on requesting va.gov DB access for VRO engineers for the moment until we have stronger confirmation that we will need it
