### ISSUE TITLE
HTML prototyping research (CodePen)

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2060]
The Employee Experience team would like to be able to do accessible prototyping for the next round of Max CFI Explorations research, and using [CodePen](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen) might be an option. We need to learn more about CodePen to determine if it's a viable option for our research needs.

## To do's
- [x] @KimLadin to reach out to Yurena and Luke on the CC team, who are experimenting with using CodePen
- [x] @dfitchett to learn more about [CodePen](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen)
- [x] @dfitchett code the green and yellow prototypes
- [x] Determine if Codepen will allow us to test with Veterans who use assistive technologies

**Comment by amylai-nava** [comment]
@KimLadin @dfitchett -- Based on notes from our team meeting today, I think you're both planning to do some further research into CodePen. Since this is not urgent, I'll leave the ticket in "Sprint Ready". Feel free to pull it in if you have bandwidth.

**Comment by dfitchett** [comment]
There's a good [thread](https://dsva.slack.com/archives/CE4304QPK/p1696008041755679) going on in slack that we could probably gleam some knowledge from!

**Comment by dfitchett** [comment]
This [doc](https://dsva.slack.com/docs/T03FECE8V/F05U48CK0LF) in slack is super useful for importing VA design system.

**Comment by KimLadin** [comment]
@dfitchett Here are the [Sketch prototypes](https://sketch.com/s/bf1a0cd3-1fae-4321-a081-82db48fa3d3a/a/oML2ogx/play) we've been testing

And here's the [Contention Classification team's Codepen](https://codepen.io/Yurena-Garcia-Hevia/pen/KKboZpN?editors=1000) that Yurena created. I don't think it's quite working yet.

**Comment by dfitchett** [comment]
Code pen is a totally viable option for generating prototypes. Since it's written in purely html, we can should be able to add in all accessibility features that we want. Here's a list of useful links:
* Max CFI prototype collection in [Codepen](https://codepen.io/collection/YyRKbV?grid_type=list)
* [VA Platform](https://depo-platform-documentation.scrollhelp.site/research-design/accessible-prototyping-with-codepen) section on accessible prototyping in Codepen
* Slack [doc](https://dsva.slack.com/docs/T03FECE8V/F05U48CK0LF) for importing VA system base into Codepen with accompanying [thread](https://dsva.slack.com/archives/CE4304QPK/p1696008041755679)
