### ISSUE TITLE
Partner Team want to call cancel on svc-bip-api, so I can remove an unnecessary claim record

### ISSUE THREAD

**Issue by greene858** [department-of-veterans-affairs/abd-vro#2098]
Team EE needs to call cancel to fulfill their  which does not include /claims/{claimId}/cancel;feature.

AC:

svc-bip-api is deployed to nonprod environments and successfully calls a nonprod BIP api
When svc-bip-api receives a cancel message, the cancel message is sent to the BIP api with the specified Claim ID.
When the call to BIP is successful, positive results are sent to the service that called svc-bip-api
When the call to BIP fails, negative results are sent to the service that called svc-bip-api
integration tests validate positive and negative calls to cancel.
all existing integration tests in svc-bip-api continue to function correctly

**Comment by nelsestu** [comment]
@greene858 @tejans24 here is what I was thinking about for this card and I am very open to the idea that I am missing a whole lot of other requirements, so please let me know if I am and we can jump on a quick call to sync up.  If this does appear to be on the right track (minor miracle) then I'll aim to get a pull request containing these changes up by this afternoon:

1. Expand [IBipApiService.java](https://github.com/department-of-veterans-affairs/abd-vro/blob/4df7a227bff18f5a2bd9acb87ac1dc84e85716e6/svc-bip-api/src/main/java/gov/va/vro/bip/service/IBipApiService.java) interface with a cancelClaimById function


2. Implement cancelClaimById function in [BipApiService.java](https://github.com/department-of-veterans-affairs/abd-vro/blob/4df7a227bff18f5a2bd9acb87ac1dc84e85716e6/svc-bip-api/src/main/java/gov/va/vro/bip/service/BipApiService.java)
I am imaging that this function implementation will contain many of the same functional elements as the updateClaimStatus call.  In other words, isn't "cancel" a claim status change that returns a slightly different CloseClaimResponse object?  If true, then this task is mostly implemented and I would wrap up by adding an integration test.

**Comment by greene858** [comment]
1. cancelClaimById does make sense, but it doesn't follow the pattern of the other functions: getClaimDetails, setClaimToRfdStatus, updateClaimStatus, etc which don't have the ...ById ending
2. We have  ...Req and ...Resp classes in the model package to match the JSON objects that the BIP API uses; e.g. CreateContentionReq, BipClaimResp, etc. I'd expect a closeClaimReq, and closeClaimResp; and I think cancelClaim uses the same JSON objects.
3. When we say "new cancel endpoint" what we are specifically talking about is enabling the svc-bip-api to listen for a rabbitMq message to cancel a specified claim ([RabbitMqController](https://github.com/department-of-veterans-affairs/abd-vro/blob/4df7a227bff18f5a2bd9acb87ac1dc84e85716e6/svc-bip-api/src/main/java/gov/va/vro/bip/service/RabbitMqController.java)), and to call the cancel endpoint on the BIP api as a client to cancel the specified claim ([BipApiService](https://github.com/department-of-veterans-affairs/abd-vro/blob/4df7a227bff18f5a2bd9acb87ac1dc84e85716e6/svc-bip-api/src/main/java/gov/va/vro/bip/service/BipApiService.java), and configs, tests, etc )

**Comment by tejans24** [comment]
@nelsestu for a context, here is the PR for the mocks: https://github.com/department-of-veterans-affairs/abd-vro/pull/2113

**Comment by nelsestu** [comment]
Thanks for having a look and for the feedback.  Especially with #3 I should have been more explicit that I wasn't exactly clear about how the routes worked but your clarification about the RabbitMQController fills in that blank.  If I have this correct now, LHDI doesn't play any roll in the routing and the OpenAIConfiguration.java class is purely for documentation purposes.  VRO takes any route passed to it and creates a RabbitMQ exchange and corresponding queue.  If we don't have anything draining that queue on the other side then it will just be an ever increasing queue length. But since our svc-bip-api container is subscribed to receive items from that queue name, we won't end up with an ever increasing queue length. Does all that ring true?

Other thoughts inline below:
> 1. cancelClaimById does make sense, but it doesn't follow the pattern of the other functions: getClaimDetails, setClaimToRfdStatus, updateClaimStatus, etc which don't have the ...ById ending
Sounds good, so I'll drop the ById ending.  Just for future understanding though, I was following the naming convention that Teja had used in the mock, but it sounds like we aren't concerned with the mock and the real handlers using the same names?  Or should we care and drop the ById from the mock as well? 

> 2. We have  ...Req and ...Resp classes in the model package to match the JSON objects that the BIP API uses; e.g. CreateContentionReq, BipClaimResp, etc. I'd expect a closeClaimReq, and closeClaimResp; and I think cancelClaim uses the same JSON objects.
I can plan on using these Req and Resp objects. I can see those in use in the mock and was planning to follow suit.  If I am understanding correctly now, cancel shouldn't a implemented as a status change as I had originally thought.  There is actually a specific cancel endpoint on the bip api and I should be calling that.

> 3. When we say "new cancel endpoint" what we are specifically talking about is enabling the svc-bip-api to listen for a rabbitMq message to cancel a specified claim ([RabbitMqController](https://github.com/department-of-veterans-affairs/abd-vro/blob/4df7a227bff18f5a2bd9acb87ac1dc84e85716e6/svc-bip-api/src/main/java/gov/va/vro/bip/service/RabbitMqController.java)), and to call the cancel endpoint on the BIP api as a client to cancel the specified claim ([BipApiService](https://github.com/department-of-veterans-affairs/abd-vro/blob/4df7a227bff18f5a2bd9acb87ac1dc84e85716e6/svc-bip-api/src/main/java/gov/va/vro/bip/service/BipApiService.java), and configs, tests, etc )
I'll aim for consistency with implementing the configs and tests and any other things I can find and if I end up missing something we can catch it in PR review.  It still feels like the OpenAIConfiguration and SecurityConfig will be part of the change set, and now the RabbitMqController feels much clearer to me, so thanks for connecting that missing element for me.
