### ISSUE TITLE
Explore a custom RDS monitoring solution so we can create a retention and storage policy 

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2116]
As a VRO Platform team member, I want to explore ways to monitor RDS through a custom solution after discovering that I do not have access to RDS metrics from LHDI.

Acceptance Criteria:

the essential metrics for monitoring are CPU Utilization, Memory, and Storage.
Outline the best approach and plan for implementing the custom monitoring solution.
Include details on tools, technologies, and methods to be used.
Provide an outline for an implementation path.
Create tickets for subsequent work as needed (if possible)
Amy mentioned whoever picks up this ticket should work with Cory on any ideas he may have. 
Collaborate with Megan to ensure this work is prioritized and integrated into the team's roadmap if possible

**Comment by dianagriffin** [comment]
Notes from team discussion: 

- What do we already know about data storage and retention needs? 
- What are the limits of budget/allocation for our use of LHDI RDS?
- What's the daily anticipated volume of contention and va.gov claim activity data?
- What's the cost/effort of configuring RDS based on what we know now and adjusting that configuration as we learn more about future needs? 
-

**Comment by msnwatson** [comment]
The engineer working on this should at least look at native Postgres DB mechanisms for achieving retention such as partitioning by date with an expiration period or submitting jobs through AWS client libraries for performing operations on DB tables.

DB schema alterations should be carefully considered

**Comment by meganhicks** [comment]
might be good to pair with Mason, Cheng or Erik

**Comment by nelsestu** [comment]
pg_cron is a custom extension for PostgreSQL that allows you to schedule jobs directly within the database. While pg_cron would provide an ideal implementation path, we need someone to validate our RDS version and validate that we can pass the appropriate [ACK config](https://aws.amazon.com/blogs/database/deploy-amazon-rds-databases-for-applications-in-kubernetes/) in through LHDI.  This is because RDS does not support installing custom extensions directly.
* RDS Version validation is needed because the pg_cron extension is supported on RDS for PostgreSQL engine versions 12.5 and higher. To verify postgres engine version you need to ssh to a dev-tools pod in production, connect to the database and run the query: `SELECT version();`
* [AWS documents the pg_cron feature here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_pg_cron.html)
	* enable the extension which is disabled by default
	* set the permissions appropriately so that the pg_cron and pg_jobs tables are made available for the VRO team to query  
* [AWS documents the AWS Controller for Kubernetes (ACK)](https://aws.amazon.com/blogs/database/deploy-amazon-rds-databases-for-applications-in-kubernetes/)
* Between flyway and helm, identify whether these RDS changes can be automated, but it isn't guaranteed
* Assuming we can automate, how long might that aspect take? that effort may not be zero time  

Some very useful examples of using pg_cron include the following:
[Collect Native Postgresql Metrics](https://github.com/DataDog/the-monitor/blob/master/rds-postgresql/collect-rds-metrics-for-postgresql.md#how-to-collect-native-postgresql-metrics-from-rds)
[pgwatch2 - a PostgreSQL metrics monitor implementation](https://github.com/cybertec-postgresql/pgwatch2)
[postgres_exporter - PostgreSQL metric exporter for Prometheus](https://github.com/prometheus-community/postgres_exporter)

From the examples listed above, confirm that we can capture all the metrics listed in the AC and feel free to specify your top recommendation.

**Comment by PaulKBaumann** [comment]
This is blocked because we need superuser access to the database in order to set up the pg_cron plugin. 

https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/43

**Comment by PaulKBaumann** [comment]
Unblocked enough to continue making progress on this research. We're still missing a way to log into the prod RDS instance

**Comment by PaulKBaumann** [comment]
Blocked again - we need LHDI to update the config in the AWS console and restart in order to install the pg_cron plugin. 

https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/70

**Comment by BerniXiongA6** [comment]
Hi @PaulKBaumann -- did you see the latest update from LHDI support ([link to support ticket with new comments](https://github.com/department-of-veterans-affairs/lighthouse-di-tenant-support/issues/70)). cc: @meganhicks @amylai-va

**Comment by BerniXiongA6** [comment]
Teams meeting has been scheduled with @PaulKBaumann @CorySohrakoffUSDS and Matt Ng (LHDI Support) to occur on Wed 10/9 1:35pm ET to discuss needs/proposed solutions to unblock this ticket. cc: @meganhicks @amylai-va

**Comment by PaulKBaumann** [comment]
Our meeting was straightforward. Matt identified an issue with our ArgoCD setup that requires the infrastructure team's involvement to address. They're looking into the issue and will get back to us when they have a solution. 

The issue is that our ArgoCD deployments aren't having the right IAM policies applied. We need that fixed before we can apply any changes to our RDS instance.
