### ISSUE TITLE
Increase RDS storage capacity

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2131]
### User Story
As a VRO engineer, I want to ensure that VRO's implementation of RDS is configured to support the forseeable storage and retention needs for VRO and our partner teams, so that partner teams who are dependent on RDS can use it.

### Details
- Confirm the default allocated storage on RDS
- Check the LHDI docs and then as needed, ask LHDI if we can be allocated a TB of storage, because that will cover our needs for the forseeable future while we continue to prioritize the effort to define a data strategy for VRO 

### Acceptance Criteria
- RDS is configured with 1TB of storage (or, the maximum amount below 1TB that LHDI is willing to allocate us 

### Definition of Done
- Any SecRel issues caused by merging changes related to this ticket have been resolved
- Documentation of VRO's RDS solution has been updated with relevant detail on storage limits

**Comment by meganhicks** [comment]
As a VRO engineer, I want to ensure that VRO's implementation of RDS is configured to support the forseeable storage and retention needs for VRO and our partner teams, so that partner teams who are dependent on RDS can use it.
New AC:
1. RDS is configured with 1TB of storage (or, the maximum amount below 1TB that LHDI is willing to allocate us



break tickets up 
1. This is ticket 1845- VRO is running on RDS 
2. . Increase storage of RDS- this ticket 
3. RDS is monitored - AC for this one: Option(s) to get metrics from CloudWatch into Datadog are documented on this ticket; if it requires action from the VRO team, that is captured in another ticket / Options to set up RDS monitoring/alerting through Datadog are documented on this ticket; if it requires action from the VRO team, that is captured in another ticket- Another AC Document how we increase storage and what we do when we start running low- what will the plan be?

**Comment by meganhicks** [comment]
M
