### ISSUE TITLE
E2E BIS testing (VRO perspective)

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2171]
### Description 
- The EE team has discovered that they will need to add claim notes to claims in tandem with using the /cancel endpoint of the BIP Claims API for their [EP Merge MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/32), in order to record the reason for cancelling the claim in a way that is visible to claim adjudicators in VBMS
- In order to add claim notes, the EE team needs VRO's BGS API microservice to be ready to support production use by a partner team application
- There are a handful of tickets needed to get the BGS microservice ready for partner team use, captured in [this milestone](https://github.com/department-of-veterans-affairs/abd-vro/milestone/37)

### User Story / Why
As a partner team engineer, I want to be able to develop my application to use the BGS microservice in the dev environment, so that I can test and validate my application as I build.

### Dependencies
- Dependent on #2172 
- Dependent on investigation into our existing BGS credentials/secrets

### Acceptance Criteria
- Validate e2e testing of the EpMerge App in Dev, QA, sandbox, prod test, prod. 
- The app should be able to successfully work with RabbitMQ and get the expected response from the VA BGS service. Test this as the VRO Team and partner with the EE Team to validate it works for them. 
- ensure the automated integration tests are documented 
- Document BGS<>VRO environment mappings and secret names & expiration dates in the vault [update existing wiki page]

### Notes about work
- [documentation of BGS service](https://dvagov.sharepoint.com/:w:/r/sites/OITEPMOIAS/dmdocsite/Legacy%20Systems%20Modernization%20LSM/LSM%20Product/Share%20(SHARE)%20-%20%231589/Benefits%20Gateway%20Services%20(BGS)%20Web%20Services.doc?d=w9e5c89b6cc71432ca4f8800921852e24&csf=1&web=1&e=0LEgjt)
- Secret assignment must be completed across LHDI environments to achieve this AC
- Pair with @nanotone

**Comment by dianagriffin** [comment]
![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/103531643/7ee6e164-5ba6-4562-a138-94a5e0452d80)

**Comment by nelsestu** [comment]
Mason has been running with the technical implementation of BGS, which is documented in [#2324](https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2324) I am assigning this issue to myself, and will continue to follow up with status details of our progress with the details of this issue.  The spirit this issue was written in, was that we wanted to prioritize testing out the auth behavior prior to finishing all the other work needed for BGS. As we got into the details of BGS, we learned the following:
* BGS is now BIS
* Dev is the wrong place to test the official auth behavior because BIS don't have authorization enabled in their lower environments.  It is not until their preprod environment that they've actually enabled auth.
* Mason is now validating our ability to connect to the BIS service in preprod - [that conversation is being tracked here](https://dsva.slack.com/archives/C04QLHM9LR0/p1707330768025619)

**Comment by nelsestu** [comment]
Some final documentation updates with regard to the BGS project: https://github.com/department-of-veterans-affairs/abd-vro/wiki/BIS-API-(formerly-BGS)
```
commit 66efa94343ab1499c9f4e5a4431a812bbf28eea7 (HEAD -> master, origin/master, origin/HEAD)
Author: Erik Nelsestuen <eriknelsestuen@navapbc.com>
Date:   Mon Mar 11 09:58:41 2024 -0600

    Updates to BIS-API docs. Additions to Datadog monitoring. Removal of unicode characters from the EE-Build-and-Deploy-Process.md file name
```
