### ISSUE TITLE
Provide capability to set temporary station of jurisdiction via BIP Claims API microservice and mock service

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2175]
**Description**
The EE Team wants to make VSRs lives easier by relieving them from having to manually merge duplicate claims. This is needed in support of EE's EP Merge MVP

**Why, What is the value?**
The EP Merge solution needs to set Temporary Station of Jurisdiction as the field will prevent NWQ from assigning the EP400 claim because that claim should not be assigned when the EE team is modifying it.

**Dependencies:** Just the pull request.

**AC:**

- If I make the call to the BIP to set Temporary Station of Jurisdiction then I will get a response from BIP that says it succeeded or failed.
- unit test and integration test passing.
- This will be integrated into the BIP API Mock service and the Mock service supports positive and negative tests
- The mock response will respond with positive, 404, and 500 messages

**Comment by meganhicks** [comment]
**Description**
The EE Team wants to make VSRs lives easier by relieving them from having to manually merge duplicate claims. This is needed in support of EE's EP Merge MVP

**Why, What is the value?**
The EP Merge solution needs to set Temporary Station of Jurisdiction as the field will prevent NWQ from assigning the EP400 claim because that claim should not be assigned when the EE team is modifying it. 

**Dependencies**: Just the pull request. 

**AC:**
- If I make the call to the BIP to set Temporary Station of Jurisdiction then I will get a response from BIP that says it succeeded or failed.
- unit test and integration test passing.
- This will be integrated into the BIP API Mock service and - The Mock service supports positive and negative tests
- The mock response will respond with positive, 404, and 500 messages

**Comment by dfitchett** [comment]
Current PR: 
* #2186

**Comment by amylai-nava** [comment]
ready for review, moving to sprint H

**Comment by dfitchett** [comment]
Currently blocked by:
* #2098
   * #2144
