### ISSUE TITLE
Investigate data storage solutions for EP Merge Jobs

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#2196]
## Summary
Ep Merge app needs to be updated with a better data storage solution for storing jobs. Currently the app just stores them in memory, which is not scalable nor reliable. We need to investigate and decide on a solution.

Possible solution is using the RDS that VRO applications should have access to (previously a dockerized postgres).

## Acceptance Criteria:
- [x] Solution is found and pitched to EE engineers
- [x] Solution is documented in a comment below ⬇

**Comment by raudabaugh** [comment]
## Solution Overview
The current merge app stores information about merge jobs in-memory, which could lead to jobs being lost if the app is suddenly terminated. To fix this, we should create a new PostgreSQL table called `jobs` based on the Pydantic `MergeJob` schema:
|Column|Type|Description|
|-|-|-|
|id|uuid|Primary key for merge job|
|pending_claim_id|int|ID for pending claim|
|ep400_claim_id|int|ID for EP400|
|state|varchar|Current `JobState` enum of merge job|

We should also create a corresponding SQLAlchemy model for `MergeJob` specifying these columns. A record for the merge job is created/updated inside `EpMergeMachine.on_transition`. Once the job enters the `COMPLETED_SUCCESS` state, remove its record from the database.

In `api.on_start_up`, we add the logic for job recovery. The proposed logic is as follows (see also Questions/Assumptions below):
- If the job state was `RUNNING_UPDATE_PENDING_CLAIM_CONTENTIONS`, abandon the job since we can't be sure if the update request completed or not.
- If the job state was `RUNNING_CANCEL_EP400_CLAIM`, resume processing the job from this state.
- For all other states that are not error/success, reset the job state to `PENDING` and restart processing.

## Change Management
Once the model is created, we have the option of applying our changes using either Flyway (VRO-supported, native SQL), or another migration tool of our choice such as Alembic. Per VRO team, we'll use the dockerized postgres for local development. Any Flyway migration we create and merge into db-init will be available in RDS. If we choose to go with another tool, we must create a new PostgreSQL schema to isolate the data, and we're on our own for developing a CI workflow that applies the migrations. For simplicity, I recommend we keep this in Flyway, but would welcome any feedback.

## Questions/Assumptions
- Are there any side effects we should be aware of related to
    - setting the temp jurisdiction more than once?
    - cancelling the EP400 more than once?
- There is a maximum of one instance of the merge app running at any time (no horizontal scaling). If/when the app is scaled out, there will need to be a method for assigning jobs from the database to instances of the app.
- How should we handle errored jobs? If job retrying is out of scope for this version, then we can probably delete those from the database after they're logged/alerted in Slack.

**Comment by dfitchett** [comment]
First off, this looks good. 👍 

Just one question: Is there a reason why you didnt include the `error_state` and any `messages` in the postgreSQL table? 

My answers to your questions regarding side effects. However, for both of these it may be worth passing these questions to @dianagriffin to ask BIP team.
* I don't believe that setting the temp station of jurisdiction more than once will have any. 
* As far as cancelling the EP400 more than once, I'm not sure if it will allow it or not, however, we can add in a call to getClaim for the EP400 and check the `claimLifecycleStatus` in the response.

**Comment by raudabaugh** [comment]
> Just one question: Is there a reason why you didnt include the error_state and any messages in the postgreSQL table?

Honestly, just an oversight on my part. Although we might not need them - is there a use case you can think of where they might help with recovering jobs?

I did consider columns for contention responses, in case we wanted to avoid re-fetching when resuming a job, but for now that seemed unnecessary.

**Comment by amylai-nava** [comment]
Marking this as done based on Derek and Yang's feedback. Implementation will be handled in https://github.com/department-of-veterans-affairs/abd-vro/issues/2197
