### ISSUE TITLE
Spike on extraschedular ratings

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2214]
Questions we are seeking to answer:
What are the VAs legal requirements in regards to supporting extraschedular ratings?
If we need approval for anything, who do we get approval from?

AC: 
We have answered the questions around what are our responsibilities for this intervention and we can communicate them with our stakeholders.

**Comment by carodew** [comment]
From Carla Here are the M21-1 guidance and 38CFR guidance related to extra schedular -
M21-1V.ii.3.A.3.a
M21-1 V.ii.3.A.2.b
38CFR 4.16
M21-1 V.ii.3.D.3
38CFR 3.321(b)(1)

**Comment by carodew** [comment]
_Note: headers are links to the relevant citations._ 

## [M21-1V.ii.3.A.3.a](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000180486/M21-1-Part-V-Subpart-ii-Chapter-3-Section-A-Determining-the-Issues#3)

![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/10144074/393bba38-2f49-4ab7-994b-8d9b715cdc11)

![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/10144074/43a1e8e2-f421-4349-bbcd-4ae709034ce9)

## [M21-1 V.ii.3.A.2.b](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000180486/M21-1-Part-V-Subpart-ii-Chapter-3-Section-A-Determining-the-Issues#3)

![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/10144074/96814bf5-de38-4cef-9c8c-0e61f4dc3fe7)

![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/10144074/7dc58f46-eab4-451c-b9d6-eb8dfe56e1b7)

## [38CFR 4.16](https://www.ecfr.gov/current/title-38/chapter-I/part-4/subpart-A/section-4.16)

(b) It is the established policy of the Department of Veterans Affairs that all veterans who are unable to secure and follow a substantially gainful occupation by reason of service-connected disabilities shall be rated totally disabled. Therefore, rating boards should submit to the Director, Compensation Service, for extra-schedular consideration all cases of veterans who are unemployable by reason of service-connected disabilities, but who fail to meet the percentage standards set forth in [paragraph (a)](https://www.ecfr.gov/current/title-38/section-4.16#p-4.16(a)) of this section. The rating board will include a full statement as to the veteran's service-connected disabilities, employment history, educational and vocational attainment and all other factors having a bearing on the issue.

## [M21-1 V.ii.3.D.3](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000180489/M21-1-Part-V-Subpart-ii-Chapter-3-Section-D-Evaluating-Disabilities%3FarticleViewContext=article_view_related_article#3)

_This is a long section, just follow the link for the full text._

Of note – 
* the examples given for what might qualify for an extra-schedular rating are frequent hospitalizations and marked interference with work. 
* ROs are _required_ to submit a claim for extra-schedular consideration when the evidence of record supports it
* Even if a Veteran specifically asks for an extra-schedular rating, ROs are only required to submit it if the evidence supports it. They _are_ required to offer an explanation to the Veteran if they don't qualify for an extra-schedular rating. 

## [38CFR 3.321(b)(1)](https://www.ecfr.gov/current/title-38/chapter-I/part-3/subpart-A/subject-group-ECFR39056aee4e9ff13/section-3.321)

(b) Extra-schedular ratings in unusual cases —

(1) Disability compensation.  Ratings shall be based, as far as practicable, upon the average impairments of earning capacity with the additional proviso that the Secretary shall from time to time readjust this schedule of ratings in accordance with experience. To accord justice to the exceptional case where the schedular evaluation is inadequate to rate a single service-connected disability, the Director of Compensation Service or his or her delegate is authorized to approve on the basis of the criteria set forth in this [paragraph (b)](https://www.ecfr.gov/current/title-38/section-3.321#p-3.321(b)), an extra-schedular evaluation commensurate with the average impairment of earning capacity due exclusively to the disability. The governing norm in these exceptional cases is a finding by the Director of Compensation Service or delegatee that application of the regular schedular standards is impractical because the disability is so exceptional or unusual due to such related factors as marked interference with employment or frequent periods of hospitalization.

**Comment by amylai-nava** [comment]
@carodew based on your review of the policy above👆🏼, I think we can consider this done! Feel free to re-open it if there was something else you wanted to do as part of this ticket.
