### ISSUE TITLE
VRO automation improvement

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#2333]
Automation in VRO infrastructure and operations has been developed haphazardly to meet individual use cases as they arise, resulting in a state where we have lots of automated scripts but we're not benefiting from them as we could be due to lack of organization and a cohesive strategy for using platform automation in ways that are helpful to us.

This epic covers the effort to define a cohesive strategy for platform automation and the follow-on tasks to implement and MVP of that strategy across existing platform capabilities. 

This epic does **not** include efforts to develop new platform automation, or automating deployments. 

#### AC:
* strategy is defined and documented, MVP tickets are created
* MVP is implemented

**Comment by msnwatson** [comment]
With an eye toward automation strategy, I want to clarify that because of some VA security policies, some things cannot be automated in a stable and future-proofed way. And I want teammates to view potential automation ideas through this lens because automations implemented in a brittle way has created more issues and confusion when the ultimately fail. There are going to be some processes that are not automatable in full and that's okay. I hope that in this epic, we can ensure we are focusing on automations that are stable and resilient to failures.
