### ISSUE TITLE
Support VRO on #2324 (Ensure BGS can authenticate in DEV)

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/abd-vro#2452]
See https://github.com/department-of-veterans-affairs/abd-vro/issues/2324 for details.

**Comment by amylai-va** [comment]
@nanotone @meganhicks I decided not to try to make https://github.com/department-of-veterans-affairs/abd-vro/issues/2324 visible on EE's board since VRO is using Zenhub now, and I'm not sure if assigning the issue a project of "Employee Experience Team" will mess anything up on VRO's side. Instead, I linked #2324 in the description of this ticket.
