### ISSUE TITLE
Deploy BGS to production

### ISSUE THREAD

**Issue by paulsackley-nava** [department-of-veterans-affairs/abd-vro#2461]
**User Story**

As a consumer of the BGS API, I want to ensure that the svc-bgs-api container can be built and deployed using accurate configuration options.  

**Acceptance Criteria**
_Note_ Please pair with another engineer on this effort
1. After validating prod-test, and confirming its viable state there, we'll plan to repeat the steps for prod. : 

**Additional Validation Work**

**Notes about work**
- _(links to documentation, resources, code, etc that might inform the person doing the work)_

**Comment by msnwatson** [comment]
In case this gets unblocked before next Friday 02/23, in order to verify successful deployment to production, you can deploy the bgs image tag published from the most recent successful run of the secrel workflow off the branch `mwatson/bgs-test`.  Because of weird log flushing issues, it might be best to wait for the pod to give a ready status and then kill the pod. After this, you can go into datadog to get all the flushed pod logs and you should see a succesful 200 call to the BGS service in the VA.

If the pod does not run succesfully to ready status or you see an error message in the logged response from the VA BGS service, then the deployment was unsuccessful and further debugging will be needed.

**Comment by meganhicks** [comment]
This is waiting on the BIS Team to unlock prod. It can stay in refinement until this is fixed

**Comment by msnwatson** [comment]
As of 03/13, deployments to both `prod` and `prod-test` are failing with an account locked error.

**Comment by msnwatson** [comment]
Moved back to Sprint Ready until accounts are unlocked in the environments. Ticket is blocked until then.

**Comment by meganhicks** [comment]
[CorpDB Application Access Final Approval - EP Merge App.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a851ceaf1bad40917bd433688a008ff4f1b60eb3/CorpDB%20Application%20Access%20Final%20Approval%20-%20EP%20Merge%20App.pdf)

Final approval
