### ISSUE TITLE
Determine how we should handles job that are in a failed state when the EP Merge App goes down

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2565]
**User Story**

As a member of the Employee Experience team, I want to ensure that we have a proper procedures in place for handling jobs that were already failing when the EP Merge App goes down so that we don't cause any delays in the processing of these claims.

**Acceptance Criteria**

- Propose the `Action Upon App Restart` for jobs that were already failing when the EP Merge App went down
- Get agreement among EE engineers & product people
- Implement it!

**Notes about this work**
- EP400 Merge App Recovery document: [link](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/employee-experience/EP400%20Merge%20Application%20Recovery.md
)

**Comment by dfitchett** [comment]
## Issue
As with any service, there is the possibility of an application going down for any reason at any time. The EP Merge App 
has a solution designed for recovering when an application was in any running state. This write-up is to investigate 
what happens when that running state was actually after the merge job had already encountered an error.  

## Current Implementation
Below is the process flow diagram for a submitted merge request. Upon submission it starts in the job state `Pending`.

![Image](https://github.com/department-of-veterans-affairs/abd-vro/assets/135860892/9b4cd541-a727-46f7-a9f0-45eaf370b431)

The current implementation covers three scenarios;
 * the job state was in the process of making the request to cancel the EP400 claim `Running cancel ep400 claim`. 
 * the job state was in the process of adding a claim note to the EP400 `Running add claim note to ep400`.
 * the job state was in **_any_** other state, including the following error states that occur after an error has occurred in one of the main steps:

| State * | Possible Error States | Notes |
|------|----------------------|-------|
| GET_PENDING_CLAIM | *_REMOVE_SPECIAL_ISSUE | No any information has been modified and failed to remove the special issue, so restart is fine.|
| GET_PENDING_CLAIM_CONTENTIONS     | *_REMOVE_SPECIAL_ISSUE | No any information has been modified and failed to remove the special issue, so restart is fine.|  
| SET_TEMP_STATION_OF_JURISDICTION  | *_REMOVE_SPECIAL_ISSUE | No any information has been modified and failed to remove the special issue, so restart is fine.|
| MOVE_CONTENTIONS_TO_PENDING_CLAIM | *_REMOVE_SPECIAL_ISSUE<br/> *_REVERT_TEMP_STATION_OF_JURISDICTION | TSOJ has been modified. After failing to move contentions to pending claim <br/> special issues _could_ have been removed, and the TSOJ _could_ have been reverted. <br/>This could be an issue now that the special issues were removed. |
| CANCEL_EP400_CLAIM | *_REVERT_TEMP_STATION_OF_JURISDICTION | TSOJ has been modified, and contentions have been moved to pending EP before failing to cancel the claim. <br/>If the job was restarted, then TSOJ would be set again, it would appear that the contentions from EP400 <br/>already exist on pending EP due to the duplicate check, so merging would be skipped, and another attempt <br/>to cancel would happen. |

**Comment by dfitchett** [comment]
In the case where we failed in MOVE_CONTENTIONS_TO_PENDING_CLAIM (second from bottom ☝ ) we attempt to remove special issues AND revert TSOJ (regardless of whether the special issues were removed). If the app fails during either of the error states (*_ _REMOVE_SPECIAL_ISSUE or * _REVERT_TEMP_STATION_OF_JURISDICTION):

Current Implementation:  job is completely restarted

Proposed implementations:
1. Leave as current implementation, maybe the contentions will be removed successfully. If the move contentions fails again: 
   * If the special issues were already removed, programmatically, it wont be an issue if they are removed again. 
   * If the TSOJ was already reverted, then it wont be an issue to attempt to revert it again since it will just be overwritten. 
2. resume the job in the *_REMOVE_SPECIAL_ISSUE state if restarted in either of these states and attempt to remove special issues again and revert TSOJ again.

I vote for leaving it the same. If the job failed to move contentions for a legit reason the first time, it will fail for the same reason, and the special issues and TSOJ will be removed/reverted (possibly for a second time), but the job will fail again either way. I don't think its worth the effort to come up with an alternative fix. The app would really have to go down at the perfect time between when a rest request is sent to BIP API and when the response is received should really only be 100s of milliseconds.

**Comment by dfitchett** [comment]
Closing, see documented decision [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/employee-experience/EP400%20Merge%20Application%20Recovery.md) and slack [here](https://dsva.slack.com/archives/C01BVF2A3V0/p1707862984306799).
