### ISSUE TITLE
Track Github action and its warnings

### ISSUE THREAD

**Issue by ponny-m** [department-of-veterans-affairs/abd-vro#2721]
As a VRO Engineer, we faced multiple warnings when it comes to deploying code through our pipelines. We investigated these warnings and fixed most of them so that we can deploy code more seamlessly. However, some workflows are still affected by this warnings:

- The following actions uses `node12` which is deprecated and will be forced to run on `node16`: `indiesdev/curl@v1.1`.
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I [contacted the engineer](https://github.com/indiesdev/curl/issues/21) in charge of maintaining this Github action, but got no response. This ticket is to maintain visibility and keep track of this issue and hopefully update it in the future. 

Github Actions workflows affected by warnings above:
1. Continuous Integration (CI) workflow => 26 warnings across various jobs
2. CI: API Gateway integration test => 10 warnings (mostly deprecated 'set-output' command)
3. CI: BIE Kafka End-2-End Test => 2 warnings
4. CI: EE - EP Merge - Integration Test => 4 warnings
5. CI: SVC BGS API integration test => 9 warnings
6. CI: SVC BIP API integration test => 2 warnings
7. Secrel => 6 warnings

Team agreed that we retired `indiesdev/curl@v1.1` action and replace it with another since it's no longer managed consistently.

**Comment by ponny-m** [comment]
`tspascoal/get-user-teams-membership@v3.0.0` is up to date and changes have been merged to `develop` branch

**Comment by Ponnia-M** [comment]
Created a new action found [here](https://github.com/Ponnia-M/curl/releases/tag/v1.0.0). Below are links to affected workflows and no more node.js 16 errors come up anymore since these actions now run on **Node.js 20**:

- [BIE-Kakfa](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8549338652)
- [BIP-API](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8549325502)
- [BGS-API](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8549324114)
- [EE-EP merge](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8549321925)
- [API gateway](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8549318454)
- [CI](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8549336960)
- [Secrel](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/8549531195) => For clarity, all `indiesdev/curl@v1.1` action warnings in our Secrel workflow have been resolved. However, the current node.js 16 warnings seen here are from another action (see picture below). Based on this [conversation](https://dsva.slack.com/archives/C04QLHM9LR0/p1710529783156679) reverting back to v5 brought back these errors. 
<img width="1582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejB6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9824f027c90f4b95e4d203367e1411c319a7c25a/Screenshot%202024-04-04%20at%201.24.09%20AM.png" alt="Screenshot 2024-04-04 at 1.24.09 AM.png" />

**Comment by ponny-m** [comment]
Created [ticket](https://github.com/department-of-veterans-affairs/github-user-requests/issues/21312) to change private repo (curl-action) to public

**Comment by Ponnia-M** [comment]
Still waiting on approval from VA COR then update this [ticket](https://github.com/department-of-veterans-affairs/github-user-requests/issues/21312)

**Comment by ponny-m** [comment]
Still waiting on approval from VA COR then update this [ticket](https://github.com/department-of-veterans-affairs/github-user-requests/issues/21312)

**Comment by ponny-m** [comment]
Created a new action in [public VA repo](https://github.com/department-of-veterans-affairs/curl-action/tree/v1.0.0). Below are links to affected workflows and no more node.js 16 errors come up anymore since these actions now run on **Node.js 20**:

- [BIE-Kakfa](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8633141398)
- [BIP-API](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8633150350)
- [BGS-API](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8633143887)
- [EE-EP merge](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8633147468)
- [API gateway](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8633135939)
- [CI](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/8633179898)
- [Secrel](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/8633190513) => For clarity, all `indiesdev/curl@v1.1` action warnings in our Secrel workflow have been resolved. However, the current node.js 16 warnings seen here are from another action (see picture below). Based on this [conversation](https://dsva.slack.com/archives/C04QLHM9LR0/p1710529783156679) reverting back to v5 brought back these errors. 
<img width="1582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejB6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9824f027c90f4b95e4d203367e1411c319a7c25a/Screenshot%202024-04-04%20at%201.24.09%20AM.png" alt="Screenshot 2024-04-04 at 1.24.09 AM.png" />

Here is the updated [PR](https://github.com/department-of-veterans-affairs/abd-vro/pull/2829).
