### ISSUE TITLE
preliminary investigation on the claims status tool

### ISSUE THREAD

**Issue by amylai-va** [department-of-veterans-affairs/abd-vro#2765]
While testing the EP400 merge process in VA.gov staging, we noticed that when an EP400 claim is canceled & combined with the pending EP020 claim, the claims status tool in VA.gov misinforms Veterans about what happened to their EP400 claim.

- It _correctly_ states that the (EP400) claim was closed
- It _incorrectly_ states that the VA has decided their claim and that a decision letter has been mailed

## Acceptance Criteria
- Do a preliminary investigation on how the claim status tool is deciding what to display
- Document findings in the comments of this ticket

## Notes about this work
- We assume that this is happening today when VSRs manually combine EP400 claims, so it should/would not block us from launching on April 1st
- It's TBD which team should address this issue post launch (EE or claim status tool team)

**Comment by nanotone** [comment]
When using the legacy EVSS endpoint to fetch claims data, we see that the returned data structure contains a claim status of `CAN`, which indicates that the claim was cancelled, and an overall "status" of `COMPLETE` indicating that no more work needs to be done.

```ruby
f526 = Form526Submission.find_by(submitted_claim_id: 600488442)
service = EVSS::ClaimsService.new(form526.auth_headers)
claims = service.all_claims.body
claims['historical_claims'].find { |c| c['id'] == "600488442" }
=>
 {"id"=>"600488442",
  "base_end_product_code"=>"400",
  "benefit_claim_type_code"=>"400SUPP",
  "claim_phase_dates"=>
   {"current_phase_back"=>false, "ever_phase_back"=>false, "phase_change_date"=>"03/14/2024"},
  "claim_status"=>"CAN",
  "close_date"=>"03/14/2024",
  "end_product_code"=>"400",
  "status"=>"COMPLETE",
  # some fields omitted
}
```

Whereas the Lighthouse Benefits Claims API, which is what the claim status tool uses, doesn't provide such nuance:
```ruby
claims = BenefitsClaims::Service.new(form526.user_account.icn).get_claims
claims['data'].find { |c| c['id'] == "600488442" }
=>
{"id"=>"600488442",
 "type"=>"claim",
 "attributes"=>
  {"baseEndProductCode"=>"400",
   "claimDate"=>"2024-03-14",
   "claimPhaseDates"=>{"phaseChangeDate"=>"2024-03-14"},
   "closeDate"=>"2024-03-14",
   "decisionLetterSent"=>false,
   "endProductCode"=>"400",
   "status"=>"COMPLETE"}}
```

It turns out that this is a [bug on the Lighthouse side](https://dsva.slack.com/archives/C04KHCT3ZMY/p1710874127104609?thread_ts=1710794341.239749&cid=C04KHCT3ZMY), and a fix is planned.

**Comment by dfitchett** [comment]
LGTM 🚀
