### ISSUE TITLE
Discovery on creating a data storage retention policy for the VRO platform 

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#2823]
As a VRO Platform administrator, I want to establish a comprehensive retention policy to efficiently manage data storage. This will ensure that our platform maintains optimal performance by storing data only for as long as it serves the benefits portfolio, thereby minimizing storage costs and maintenance overhead. 

This ticket is specifically designated for conducting discovery work, as decided by the team during our recent backlog refinement session. The focus of this discovery work will deviate from traditional technical specifications we do normally and instead aim to address the following questions within a time frame of 3 days, ensuring efficient progress.

Acceptance Criteria: 

- This initiative will encompass all data, not solely personally identifiable information (PII).
- Given that VRO will own and manage this initiative, it necessitates the implementation of appropriate monitoring and alerting systems.
- Provide a recommendation on the optimal approach to implementing a one-year data retention blanket policy across all of VRO's systems, including applications utilized by Partner Teams.
- Ensure that this recommendation considers any ongoing queries that are in progress.
- Ensure the data meets the VA policies listed under notes.
- Ensure partner teams are taken into account
- Update the ticket linked below with the proposed solution and present it during a backlog refinement session for prioritization.
- Timebox: 4 days 

Out of scope: 
-partner team comms plan

Notes: Current PIA says this:
VRO does not retain information, however, source systems comply with all VA retention and disposal procedures specified in VA Handbook 6300 and VA Directive 6500 in accordance with a NARA-approved retention period. VA manages Federal records in accordance with NARA statues including the Federal Records Act (44 U.S.C. Chapters 21, 29, 31, 33) and NARA regulations (36 CFR Chapter XII Subchapter B). VRO does not retain information, however, source systems records are retained according to [VBA Records Control Schedule, VB-1, Part I](https://benefits.va.gov/WARMS/docs/admin20/rcs/part1/VB-1Part-I.doc) and [VBA Records Control Schedule, VB-1, Part II](https://benefits.va.gov/WARMS/docs/admin20/rcs/part2/VB-1PartII.doc).

**Comment by lisac** [comment]
this work will carry over into Sprint V

**Comment by BerniXiongA6** [comment]
Thanks for the heads up @lisac cc: @meganhicks

**Comment by lisac** [comment]
I approached this as four questions:
Q1. Is it acceptable for VRO to delete data in its system?
Q2. If so, what would be a reasonable retention policy?
Q3. What controls are available to implement such a policy?
Q4. What are the next steps?

### Q1. Is it acceptable for VRO to delete data in its system?

Given this as the VRO data footprint: two (2) tables stored in a database (RDS in VAEC)
 	- `bie_contention_event` : a subset of data pulled from Event Bus
 	- `merge_jobs`: pairs of claim IDs that warrant further processing (which itself happens outside of VRO); and meta data about the processing status

Considering that the [Event Bus PIA](https://department.va.gov/privacy/wp-content/uploads/sites/5/2024/05/FY24EnterpriseEventBusPIA_508.pdf) indicates key information is retained for a period of no longer than seven days:
> Events that include information listed in 1.1 [Characterization of the Information] are retained for a default period of no longer than seven days in the Kafka instance. This should provide adequate time for any consuming systems to pick up the event. See this Event Retention discussion for more details: https://github.com/department-of-veterans-affairs/VES/blob/master/research/Event%20Bus/Engineering/ADR/ADR%20event%20design.md#event-retention

...and that the Event Bus team's discussion highlights motivations not unlike VRO's:
>  Event Bus Administrators want the retention period to be relatively short, as this reduces the time the data remains in our system and decreases the amount of data that needs to be stored. Consuming Systems want the retention period to be long enough such that they will be able to process the stream of events before they expire. (If they end up being responsible for the cost of storing the events that they produce, producing systems are likely to want to reduce the retention period to keep costs down). (source: see the github page link

Considering that VRO is not a System of Records

Considering that table `merge_jobs` serves as a coordination point with systems of record
...and assuming that any coordination task is processed within one week of its instantiation


Yes, it is acceptable for VRO to delete data that it has ensured programmatically or by policy is not needed to operate the system.


### Q2. If so, what would be a reasonable retention policy?

The acceptance criteria for this discovery work suggests a one-year data retention blanket policy. 
Considering the Event Bus retention policy of seven days and viewing VRO as acting like a cache of Event Bus data of interest to VRO partners, it would be difficult to argue for a VRO retention policy of less than seven days. One year is a relatively conservative period, while still having a visible effect.

One-year is a reasonable retention policy. 

### Q3. What controls are available to implement such a policy?

VRO uses an AWS PostgreSQL RDS running in the VA Enterprise Cloud. Built into the managed database model, we benefit from AWS handling db snapshots (backup copies) and logging. Thus a VRO retention policy should consider the RDS instance; db snapshots; and log files.

Regarding db snapshots, the maximum period is 35 days ([ref](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html)). Regarding log files, the maximum period is 7 days ([ref](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html)). In one view: it is true that neither will hold onto data beyond a one year period. As for the perspective of a retention policy as a guarantee of how long data will be available: this is not true. However, I propose that db snapshots and log files should be exempt from the latter, as they are replaced on a rolling basis and in most cases of use for only a limited window (more likely that we would restore from a db snapshot from 2 hours ago or 2 days ago rather than restore from a db snapshot that's 22 days old).

Regarding the records in RDS, these options were assessed:

option | pros | cons 
---|---|---
`pg_partman` + `pg_cron`: leverage PostgreSQL’s native range partition | most scalable; general support by AWS ([blog](https://aws.amazon.com/blogs/database/archive-and-purge-data-for-amazon-rds-for-postgresql-and-amazon-aurora-with-postgresql-compatibility-using-pg_partman-and-amazon-s3/)) | most complex to troubleshoot/maintain 
`pg_cron` to run a custom script on a schedule, ultimately keying off of `createdAt` or `updatedAt` on `bie_contention_event`'s [BaseEntity](https://github.com/department-of-veterans-affairs/abd-vro/blob/develop/shared/persistence-model/src/main/java/gov/va/vro/persistence/model/BaseEntity.java#L30), corresponding timestamps on [`merge_jobs`](https://github.com/department-of-veterans-affairs/abd-vro/blob/09202ca9bf4abe33a106074d83c4e88792051391/domain-ee/ee-ep-merge-app/src/python_src/model/merge_job.py#L19) | relatively low complexity db manipulation; general `pg_cron` support by AWS [docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_pg_cron.html) | unlikely to be as performant as deletion by partition
`pgAdmin` to run a custom script on a schedule. similar script as used in the `pg_cron` approach, but using a standalone [app](https://www.pgadmin.org/download/) in place of `pg_cron` | relatively low complexity db manipulation |  unlikely to be as performant as deletion by partition; introduces one more tool to the VRO ecosystem | 
task runner external to RDS to run a custom script on a schedule. similar script as used in the `pg_cron` approach, but using a task runner service already used by the team (eg GH Actions) in place of `pg_cron`.  | relatively low complexity db manipulation | unlikely to be as performant as deletion by partition; (potential con) increased complexity in that at least 2 systems are coupled in order to execute the task (2 is harder to coordinate than 1)

All have this assumption: VRO has - or would be able to request from LHDI - a db user account with DELETE permissions.

Personal recommendation: rows 2 or 4. 

### Q4. What are the next steps?
1. Verify assumptions
   - VRO has - or would be able to request from LHDI - a db user account with DELETE permissions.
   - any record in `merge_jobs` is processed within one week of its instantiation
2. Team decision on implementation approach.

**Comment by meganhicks** [comment]
Hi Lisa, I am going to set up 30 min to talk through your findings.
