### ISSUE TITLE
Gracefully offramp EP Merge requests with inactive special issues

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#2950]
Currently we don't have a way to perform EP400 merges if the EP has an inactive special issue. We should consider these EPs ineligible for merge, and handle them gracefully so that the alerts channel has better signal on actionable failures.

**Acceptance Criteria**

~~1. Compile list of inactive special issues from [#benefits-ee-ep400-alerts](https://dsva.slack.com/archives/C067L5WK9K6) messages seen so far (including `PDE` and `BDE`)~~
~~2. Offramp EP Merge jobs when an inactive special issue is seen on the EP400.~~

- [x] Display a chart on the datadog [dashboard](https://lighthousedi.ddog-gov.com/dashboard/unv-vap-yeb/employee-experience-ep-merge-vro-platform?fromUser=true&refresh_mode=monthly&view=spans&from_ts=1714546800000&to_ts=1715636971810&live=true) which shows the special issue codes that caused failures. 
- [x] Modify monitor so that only failures caused by reasons other than deactivated special issues alert on [#benefits-ee-ep400-alerts](https://dsva.slack.com/archives/C067L5WK9K6)
- [x]  Display a number of failures caused by deactivated special issues. Separate these numbers from total failures upon weekly Wednesday COB summaries.

**Comment by dfitchett** [comment]
After a discussion with @nanotone, while we both agree that eventually EP Merge App should be updated to include an ABORT state along with SUCCESS and FAILURE, the task is not a small undertaking. We decided the main goal of this task is really to declutter the [#benefits-ee-ep400-alerts](https://dsva.slack.com/archives/C067L5WK9K6) channel for alerts related to failures due to deactivated special issue codes.

Because of this, the acceptance criteria has been modified in the summary above.
