### ISSUE TITLE
Create VRO Datadog monitor for EP Merge volume

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#2952]
**User Story**

As a member of the EE team, I want to be notified in Slack when the volume of (successful) EP400 Merge jobs falls below expected trends (as of 100% rollout on 2024-05-06), so that I can proactively investigate and escalate if necessary.

**Acceptance Criteria**

1. Create VRO Datadog monitor to check that the number of successful merges falls within expected trends
2. Create VRO Datadog monitor to check that the percentage of failed merges stays below some fairly low threshold
3. Integrate monitors with #[#benefits-ee-ep400-alerts](https://dsva.slack.com/archives/C067L5WK9K6)

**Notes about work**
- Let's have a discussion about what time ranges and thresholds make sense for configuring these monitors, given the traffic profile of EP Merge.

**Comment by dfitchett** [comment]
AC1:
* [Zero Successful Merge Jobs](https://lighthousedi.ddog-gov.com/monitors/230839) will alert if the past 12 hours have 0 successful merges. We don't have enough information to determine what non-zero number would be a better threshold, and we dont have enough data to determine what an expected trend is.

AC2: 
* [EP Merge: High Failure Rate (past 8hr)](https://lighthousedi.ddog-gov.com/monitors/231458) will alert if the past 8 hours have a failure rate greater than or equal to 25%. This threshold can be adjusted as necessary as we get more requests. I chose 8 hours for this so that we might get an alert during working hours.
