### ISSUE TITLE
Epic: Enable EP Merge for multiple contention claims

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3001]
The [EP400 Merge MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/32?closed=1) was narrowly scoped to work on claims for increase (with only one condition). 

As a next step, we'd like to expand this functionality to any claim with multiple conditions (_new claims_ and _claims for increase_)

## **User Story**

As a VSR, I want any multiple contention EP400 claim to be combined with the Veteran's existing pending claim, so that I do not have to manually combine them.

## **Acceptance Criteria**
(Pulled from: https://github.com/department-of-veterans-affairs/abd-vro/issues/2052)
1. If the claim meets all eligibility criteria, send it to VRO EP Merge and https://github.com/department-of-veterans-affairs/abd-vro/issues/2053
2. If the claim does not meet all eligibility criteria, then no action is taken and the claim will be processed normally
3. [TBD] -- launch plan? (all at once? phased rollout?)
4. [TBD] -- comms strategy? (who needs to know? are there SME's we should consult?)
5. [TBD] -- testing strategy? 

## **Eligibility Criteria**
(Pulled from: https://github.com/department-of-veterans-affairs/abd-vro/issues/2052)
- The EP400 has multiple contentions and is a _**new claim**_ or a **_claim for increase_**
- The contentions on the EP400 have contention classifications
- The Veteran only has 1 pending rating claim
_(relevant rating EPs are: 010, 110, 020, 030, and 040's + any incremental EPs like 031s and 041s)_
- The pending claim is an EP010, 110, or 020

## **Notes about work**
- We're dependent on the CC team's work of routing multiple contention claims:
    * https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/472
    * https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/471
    * https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/480
- https://github.com/department-of-veterans-affairs/abd-vro/issues/2785
- https://github.com/department-of-veterans-affairs/abd-vro/issues/2052

**Links**
- [Milestone: EP400 Merge MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/32?closed=1)
- [Milestone: EP400 Merge Post-MVP](https://github.com/department-of-veterans-affairs/abd-vro/milestone/40)

**Comment by dfitchett** [comment]
Couple of notes about this work: 
* EP Merge should be able to handle contentions with multiple contentions without any changes. We don't have a test that explicitly covers moving multiple contentions to the pending claim, but we do have a [unit test](https://github.com/department-of-veterans-affairs/abd-vro/blob/6d22e47bec16146db6b5544ed48688d179e8e4fc/domain-ee/ee-ep-merge-app/tests/service/test_ep_merge_process.py#L1011) for EP400 that covers a claim that has multiple contentions but one of them is already on the pending EP. We could add more, but i don't think that its necessary since the `ContentionsUtil` class's simple logic handles multiple contentions.  
* `vets-api`: 
  * The work involved in vets-api is dependent on progress that team CC makes on supporting multi-contention claims. Blocking tickets:
    * https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/472
    * https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/471
    * https://github.com/department-of-veterans-affairs/vagov-claim-classification/issues/480
  * Contention classification already supports NEW / increase contentions. The eligibility to send requests to EP Merge via `prepare_for_ep_merge!` needs be updated. Currently the `update_classification!` only handles processing a single contention (both new and CFI) and returns a boolean value of whether the contention_code is updated in the form. 
  * In order to process EP400s, all the contentions will need to have their contentions classified. Currently, we only prepare for ep_merge if there is a single CFI contention with classification.
