### ISSUE TITLE
Application Alerting for BIP

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3017]
As a member of the VRO platform team responsible for supporting partner teams, I need to be alerted about any connectivity issues with BIP. This will allow me to proactively notify partner teams about potential interruptions in their services

## Acceptance Criteria:

- [x] When the monitor for BIP detects a disconnect or significant delay in service there is an alert that is triggered notifying the team. 
- [x] Share why the thresholds were chosen to the team in slack

## Implementation / Developer Steps (to be filled out by ticket assignee)
linked ticket-https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2932

**Comment by dfitchett** [comment]
Current Monitors can be viewed on this [dashboard](https://lighthousedi.ddog-gov.com/dashboard/imt-ubp-z29/vro-data-services-bip?fromUser=false&refresh_mode=sliding&from_ts=1727466853565&to_ts=1727470453565&live=true). They need to be re-evaluated for accuracy.

**Comment by dfitchett** [comment]
[Datadog Dashboard](https://lighthousedi.ddog-gov.com/dashboard/imt-ubp-z29/vro-data-services-bip?fromUser=true&refresh_mode=sliding&from_ts=1725227499039&to_ts=1727819499039&live=true)
 
For this ticket, I did the following:
* Updated Monitor: [VRO : BIP Elevated Average Latency](https://lighthousedi.ddog-gov.com/monitors/254966)
  * Lowered threshold for alert to 1500ms, removed threshold. High latency indicates issues with downstream BIP claims API. 
* Updated Monitor: [VRO : BIP non-2xx responses](https://lighthousedi.ddog-gov.com/monitors/242346)
  * Lowered threshold to 1 non-2xx response since any error should be looked into
* Added monitor overlay for `VRO : BIP Elevated Average Latency` to request duration chart in dashboard
