### ISSUE TITLE
Application Alerting for BGS

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3018]
As a member of the VRO platform team responsible for supporting partner teams, I need to be alerted about any connectivity issues with BGS. This will allow me to proactively notify partner teams about potential interruptions in their services

## Acceptance Criteria:

- [x] When the monitor for BGS detects a failure (upstream or downstream) or significant delay in service there is an alert that is triggered notifying the team. 
- [x] Work with the EE Team or Derek to determine the right thresholds 
- [x] Explain why the thresholds were selected in slack to the team
- [x] Update datadog [dashboard](https://lighthousedi.ddog-gov.com/dashboard/9kd-u35-dxv/vro-data-services-bgs) to be able to filter by new tags.
- [x] Update monitors to filter by new tags.

## Implementation / Developer Steps (to be filled out by ticket assignee)

Linked ticket-https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2980

**Comment by dfitchett** [comment]
Modifications/Updates for this ticket:
* Made alert threshold > 0 for this [monitor](https://lighthousedi.ddog-gov.com/monitors/238120) than sends notifications to [#benefits-vro-alerts](https://dsva.slack.com/archives/C044ZL0PKLL) when downstream BGS returns a response error.
  * Zero threshold was applied here because if the failure happens there is no retry mechanism, and a single failed request will need to be manually fixed by our VA partners in VBMS. 

Updating Dashboards / Monitors to use new tags for filtering is blocked by deployment to those environments.
