### ISSUE TITLE
Implement DC-specific Max CFI logic without hyphenated codes

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/abd-vro#3230]
In lieu of completing #3066 all in one go, which requires hyphenated codes data to be available (via the migration from EVSS to the Lighthouse Veteran Service History and Eligibility API), implement just the parts of #2784 which can be done without hyphenated codes:

### Acceptance criteria

- If the primary diagnostic code belongs to one of the following body systems, do not display a max rating:
  - Digestive (DCs 7200-7399)
  - Infectious Disease (DCs 6300-6399)

**Comment by KimLadin** [comment]
@nanotone:

For Digestive system, we can limit the excluded DCs to:
7318 Cholecystectomy (gallbladder removal), complications of (such as strictures and biliary leaks)
7319 Irritable bowel syndrome (IBS)
7327 Diverticulitis and diverticulosis
7336 Hemorrhoids, external or internal
7346 Hiatal hernia and paraesophageal hernia

For other Digestive diagnostic codes, we can show the max ratings intervention where appropriate.

The excluded DCs were selected because they were most likely to be hyphenated with other codes that could offer a higher rating.
