### ISSUE TITLE
Condition-specific intervention investigation

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3398]
Notes from sprint planning on “Condition-specific intervention” (CSI) … 
- Confirmation on doing this in the first place
- Narrow down the intervension for new, classifieable contentions?
- Ability to map conditions to diagnostic codes OR could we use classification codes instead?
- Look into using contention events – HMW alleviate the contention vs. rated disability mismatch issue with these?
- Is the intervention based on the classification code (we will have at the time) vs. the diagnostic code (which we won’t have at the time).
- QUESTION: can we even show condition-relevant content while someone is filling out the 526?
- Cross-reference this with number of claims submitted.

Acceptance Criteria### 

- [x] Determine the output format. On the spectrum from comment on this GitHub ticket <--> formal tech spec.
- [x] Answer the question "can we show condition-specific info while someone is filling out the 526?"
- [x] Assumptions
- [x] Open questions that need answers
- [ ] Suggested approaches with pros/cons/tradeoffs
- [ ] Next steps (including team sharing)

**Comment by nanotone** [comment]
## On contention classification codes and diagnostic codes

When adding a new condition to an in-progress 526 form on [va.gov](http://va.gov/), the Veteran provides a description of the condition, either from a pre-populated list or as free text. Upon 526 submission, this description is used by the CC API to determine the contention classification code which informs downstream processes, like what kind of medical exam is needed.

Notably, the classification code is *not* the diagnostic code, which is assigned when the RVSR creates a disability rating. Generally, classification codes are broader than diagnostic codes. For example, classification code 8979 indicates Heart/Veins/Arteries and corresponds to many possible diagnostic codes.

(It *may* still be conceivable that two contentions with different classification codes can end up with the same diagnostic code, since the actual rating is up to the RVSR. This feels unlikely, but I just haven’t seen any rule that prohibits this.)

Assuming there exists a one-to-many mapping between a classification code and multiple diagnostic codes, can we just use classification code to decide which condition-specific EOC education to show? Unfortunately:
- Classification code 8979 encompasses hypertension as well as many other cardiovascular conditions
- Classification code 3140 encompasses tinnitus as well as... hearing loss other than tinnitus 🤦 

However, the CC API can potentially incorporate the original description inputed via the UI to return a best-effort guess at which condition was intended, often with diagnostic code specificity. In fact, this "UI term" mapping underlies the CC team's master condition list which powers the CC API. Here is a summary (probably incomplete) of this master condition list mapping for classification codes 3140 and 8979:

- CC 3140: Hearing Loss
  - DC 6100 hearing loss other than tinnitus
  - DC 6260 tinnitus
- CC 8979: Heart/Veins/Arteries
  - DC 7000 valvular heart disease
  - DC 7005 arteriosclerotic heart disease
  - "Arrhythmia group"
    - probably DCs 7010 supraventricular tachycardia, 7011 ventricular arrhythmias
    - but not DC 7009 bradycardia?
  - DC 7010 supraventricular tachycardia
  - DC 7017 coronary bypass surgery
  - DC 7101 hypertension
  - DC 7120 varicose veins
  - DC 7124 Raynaud's disease (primary Raynaud's)

The takeaway here is that both tinnitus and hypertension can be reliably identified from the UI term, assuming the Veteran selected from the pre-populated list, rather than providing a bespoke description that doesn't match any UI terms. Certain UI terms still do _not_ map to a single diagnostic code, as with the "Arrhythmia group", and it is likely that diagnostic code specificity will never be available for conditions in these groupings, at time of 526 submission.

Please reach out to me or Yurena if you'd like to peruse the master condition list with all the UI terms.
