### ISSUE TITLE
Deeper technical investigation into Flashes + Special Issues

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3458]
Opportunity brief here: https://docs.google.com/document/d/1jV9ZKV80kLzVd3fodUFeoqsJkiLO7-MU0I-VkitHQw0/edit?usp=sharing

### High-level Goal 
To understand which special issues and flashes are attempting to be set and whether that logic is functioning correctly.

### Description
Following up on @nanotone's initial research on Flashes: https://github.com/department-of-veterans-affairs/abd-vro/issues/3452, we'd like to understand more about the **Special Issues** side of the equation. For some additional context here, [David K indicated that](https://docs.google.com/document/d/1jV9ZKV80kLzVd3fodUFeoqsJkiLO7-MU0I-VkitHQw0/edit#heading=h.6zp6s7iqit9j) "...additional Special Issues that are currently applied in va.gov claims will no longer be applied when the transition from EVSS to Lighthouse is completed."

### Acceptance Criteria
1. Briefly research what we know/can discover about how special issues move through the system (duplicate research but for special issues) 
2. Summarize below in a comment
3. Anything else we think of doing now to get us closer to the above goal? See the [Discovery section of the brief](https://docs.google.com/document/d/1jV9ZKV80kLzVd3fodUFeoqsJkiLO7-MU0I-VkitHQw0/edit#heading=h.nefwdo8z3ugu).

**Comment by nanotone** [comment]
Technical discovery on how special issues are applied by va.gov's 526 form:

Basic background - special issues are tags that can be added to contentions, signifying some special handling downstream regarding either the contention or the claim as a whole.

Note: Outside of flashes at the Veteran level, and special issues at the contention level, there is no mechanism to tag a claim as a whole, which is why claim-level tags (like `EMP` for EP400 Merge) are implemented as special issues.

Many learnings are indebted to [prior discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/special_issues_discovery.md) done by the DBEX team.
- On a Form526Submission, vets-api can add special issues to a contention by including a `specialIssues` array on the disability object.
  - These are initially populated by special issues sent from the frontend, which must be in [this list](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/cbff1da/src/schemas/21-526EZ-allclaims/schema.js#L123) in the JSON spec. Currently, [POW](https://github.com/department-of-veterans-affairs/vets-website/blob/526e679/src/applications/disability-benefits/all-claims/submit-transformer.js#L79) is the only such example.
  - The vets-api backend can add special issues of its own. Currently, [EMP](https://github.com/department-of-veterans-affairs/vets-api/blob/f04002f/app/models/concerns/form526_claim_fast_tracking_concern.rb#L325) is the only such example.
- EVSS, which is currently the middleware between vets-api and VBMS that actually establishes claims, imposes its own list of allowed special issues: ALS, GWPAH, HEPC, POW, PTSD_1, PTSD_2, PTSD_4, PTSD_3, RRD, PACT, EMP (as of [March '24](https://dsva.slack.com/archives/C1VBAHWQL/p1709743385928179?thread_ts=1709238467.657079&cid=C1VBAHWQL)). Turn-around time to make changes to this logic is on the order of weeks.
- Lighthouse's [Benefits Claims API](https://developer.va.gov/explore/api/benefits-claims) is slated to replace EVSS imminently, and [plans to support](https://dsva.slack.com/archives/C02CQP3RFFX/p1715697713258179?thread_ts=1709239412.795819&cid=C02CQP3RFFX) both `POW` and `EMP` in v2. Turn-around time to make changes to this logic is also on the order of weeks. Additionally, there appears to be little/no intention to let API consumers (e.g. vets-api) specify arbitrarily many special issue types.
