### ISSUE TITLE
Understand how VRO's system or applications going down impacts partner team claims processing

### ISSUE THREAD

**Issue by bianca-rivera** [department-of-veterans-affairs/abd-vro#3477]
Description

As a stakeholder, I need to understand how any VRO platform malfunctions could impact the EE Team and the CC Team, particularly in relation to the EpMerge App and Contention Classification Application. This will allow VRO to identify if any silent failures could affect claims processing and determine if remediation is required before November 12th.

Acceptance Criteria:

Talk to the EE and CC Teams to understand how failures in their applications ultimately impact veterans and claimants.
Document Findings

**Comment by dfitchett** [comment]
Associated EE ticket: #3491

**Comment by dfitchett** [comment]
After speaking with @tyler-spangler6, we concluded that the only possible ill-effect that a VRO downtime has on the classification contention application is that a claim would not have the contentions classified when the claim is established. 

If a contention is created with a null classification, then other downstream services or a VSR is responsible for adding the contention classification. This reliance on downstream services or a VSR is the same if the contention cannot be classified by the CC app. 

Therefore, the impact if VRO has a downtime is pretty minimal. 

Request metrics (success / failure) to services within VRO are captured on this VA Datadog [dashboard](https://vagov.ddog-gov.com/dashboard/jxx-zc4-zqk/benefits-vro-virtual-regional-office-endpoints?fromUser=false&refresh_mode=sliding&from_ts=1726774338379&to_ts=1727379138379&live=true) and monitors are in place to notify when requests begin to fail, with the alerts being sent to the CC team's channel [#benefits-cft-classification-alerts](https://dsva.slack.com/archives/C05GK44FL5D)

**Comment by dfitchett** [comment]
EE shares the same concerns when faced with a VRO downtime on both the Max Ratings API (max-cfi) and Ep Merge.

Additionally, since the EP Merge App also relies on downstream services BIP Claims API (made available through `svc-bip-api` and BGS Notes Service (made available through `svc-bgs-api`), there are the following additional concerns:
* If VRO RabbitMQ or RDS connection is down:
  * EP Merge jobs will immediately fail to accept new jobs returning a 500 to`vets-api`
* If `svc-bip-api` is down:
  * Upon initialization of merge job, messages sent through rabbitmq will immediately timeout given the TTL and be dead lettered (if applicable, as of the date of this comment, it is not) and the message will be retried 30 seconds later for 2 more requests. If the service still does not respond, the merge job will fail and notifications sent to [#benefits-ee-ep400-alerts](https://dsva.slack.com/archives/C067L5WK9K6) slack channel.
  * If the job has proceed up to the point of making modifications by changing the contentions or setting the temporary station of jurisdiction `svc-bip-api` goes down during the job, the same retry mechanism will be attempted, and if unsuccessful, the job will fail and send notification to the slack channel above. **These jobs require manual intervention and processing by someone with VBMS production access.**
  * If downstream BIP Claims API is down for any step in the EP Merge job or some other error response is given, that response is passed back up to EP Merge through rabbitmq, and the same error processing described above is followed.
* If `svc-bgs-api` is down:
  * The EP Merge job will have proceeded to reach the point where all modifications have been made to the claims and the EP400 claim has been cancelled. The call to add the note will fail to reach the `svc-bgs-api` and no note will have been added to the EP400 claim, and this will **require manual intervention and processing by someone with VBMS production access.**
  * If downstream BGS is down or responds with error responses, that response is passed back through to the EP Merge app and the merge job is failed.  **These jobs require manual intervention and processing by someone with VBMS production access.**

## Failures Investigation Results #3491 
This [link](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/VRO%20-%20Virtual%20Regional%20Office/Silent%20Failures/ep_merge_silent_failures.xlsx?d=w110db286373e437bb5f483a4ac049985&csf=1&web=1&e=2OBSAV) provides the ep merge jobs that completed in error in the EP Merge app. Red lines need remediation, yellow lines result from failures, but do not require remediation

Impacts of downstream VRO failures:
* `svc-bgs-api` failures: 7 Failed, 7 with remediation need
* `svc-bip-api` failures: 35 failed, 5 with remediation needed

Note that the above failures could be due to RabbitMQ failures as well.

Of the remediations above, one of them was suspected to be a silent failure: Meaning that this possibly resulted in erroneous actions performed on the claim, and these errors were not alerted upon.

* The claim had already been worked and closed with some possibly missing information as a result.
* Initially it looked like the EP merge modified the claim with erroneous actions
* After digging into this further, we discovered that the changes made to the claim were by a VSR that was working the claim. Some more investigation needs to be done, but it's looking like this is not a silent failure.

To date, NO Silent Failures have been discovered, and the failures above were just not acted upon. 

Questions asked in response to the investigation:
1. What was the impact on Veterans?
2. What do we need to do in the future to prevent this?

Answers:
1. I don't believe there was any impact to any veterans regarding their claims. The actions that Alejandro took on the claims were one of the following:
    * Making sure that the claim note was present on the EP 400s that were successfully cancelled,
    * Cancelling the EP400 and adding the claim note. The contentions here would have already been successfully moved over.
2. We already have error handling and monitoring in place to correct these as they come up. The few here were ones that slipped through. Now that we have silenced most of the errors related to claims that were not eligible in the first place, there will be far fewer failed jobs (only 4 in the past week with 1 requiring action, already done). Any failed jobs that happen will send a notification to [#benefits-ee-ep400-alerts](https://dsva.slack.com/archives/C067L5WK9K6). I created a [canvas](https://dsva.slack.com/canvas/C067L5WK9K6) in that channel that has instructions on how to appropriately mark these notifications as they come up. There are 10 people in that channel, and I've confirmed with [@Mack](https://dsva.slack.com/team/U071H7JSZNV)
 and [@yang (he/him)](https://dsva.slack.com/team/UP84XNUBY) that they do not have it muted, so the chances of it being missed are low.

## More Resources
More information and discussion can be found in the following places:
* #3491 
* More on remediation steps taken in #benefits-employee-experience in this slack [thread](https://dsva.slack.com/archives/C01BVF2A3V0/p1727278764374829).
* Reported to #benefits-vro channel in this slack [thread](https://dsva.slack.com/archives/C04PKJ7FQCE/p1727370862594029).

**Comment by BerniXiongA6** [comment]
Hey @dfitchett could you size this after the fact so that we can get this captured in sprint 2 delivery metrics? Thank you!
