### ISSUE TITLE
Design or tech spec for the potential VRO-based solution for adding Special Issues

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3538]
Though we heard from Alejandro that "Flashes are probably more impactful to Vets", we know that MAS applies some Special Issues that va.gov does not, which is an oversight/technical debt, and that "sometimes Flashes and Special Issues go hand in hand".

Therefore, we'd like to design/architect a solution for applying Special Issues, as a solution on top of VRO, since we think this makes the most sense as a solution here.

See [Flashes + Special Issues Planning Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727297726171/6a772263c4577f5697c52cf7eb2055d76e426833?sender=uf3d2a9320ea286a502077710)

**Comment by dfitchett** [comment]
# Special Issue Codes
Using [Appendix E. Index of Corporate Flashes and Special Issues](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000179710/Appendix-E-Index-of-Corporate-Flashes-and-Special-Issues%3FarticleViewContext=article_view_related_article#2f) as the starting point for understanding what circumstances should result in flashes being added

Implementation notes: 
* Special issue codes can only be applied once to any contention
* From [III.i.2.F.2.f.](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000046277/M21-1-Part-III-Subpart-i-Chapter-2-Section-F-Record-Maintenance-During-the-Development-Process#2):
  * > Special issues indicators may need to be updated throughout the life of a claim.  It is important that claims processors are vigilant in identifying when the circumstances of the claim require the addition, removal, or editing of special issue indicators.
* The BIP Claims API endpoint to get contention summaries does not reliably return the `diagnosticTypeCode`, ie 6260 for tinnitus. Additionally the `classificationType` (i.e., 9007 for ALS and other neurological other systems) is not a required field, but will be present for contentions that are successfully classified by CC's tool. BIP Claims API `classificationType` == CC `classification_code` and BIP Claims API `claimantText` == CC `classification_name` if the CC tool was used to successfully classify. 
* Unless otherwise noted, the special issues to be added must be added via VRO's integration with BIP Claims API to modify the contentions after they are created. 

### Amyotrophic Lateral Sclerosis (ALS) -- Also a FLASH at the claim level

Flash info: 

>> Apply when a claim for benefits involving Amyotrophic Lateral Sclerosis (ALS) is received and remove if the claim is denied due to no diagnosis of ALS.
>* Implementation: apply flash when a contention for increase has DC 8017 or a new contention is classified as ALS
The classification for ALS is 9007 (Neurological other System), which also includes other conditions like dysphagia, fibromyalgia, migraines, etc. So it is not possible to identify ALS with the current CC API; it would need to return the matching UI term. See https://github.com/department-of-veterans-affairs/abd-vro/issues/3398#issuecomment-2321593481

Special Issue: 

> Use for ALS claims when entitlement has not been previously established.

**Implementation**: Apply the special issue to a rated contention or new condition, if the contention details returns a contention with `"classificationType":9007` and `"claimantText":"ALS (amyotrophic lateral sclerosis)"` then the special issue can be added if it is not already on the contention.

<hr/> 

### Military Sexual Trauma (MST)
>Use for any condition(s), mental or physical, (including posttraumatic stress disorder (PTSD)), resulting from MST.  
>
>Reference:  For more information, see [M21-1, Part VIII, Subpart iv,1.B.1.c](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177469/M21-1-Part-VIII-Subpart-iv-Chapter-1-Section-B-Development-for-Posttraumatic-Stress-Disorder-PTSD-Claims-Related-to-Personal-Trauma).

This one will likely be too difficult to automate because it's very heavily based on the evidence supplied by the veteran. See [MST Claim Processing Requirements](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177469/M21-1-Part-VIII-Subpart-iv-Chapter-1-Section-B-Development-for-Posttraumatic-Stress-Disorder-PTSD-Claims-Related-to-Personal-Trauma).

To be eligible for [PTSD disability compensation](https://staging.va.gov/disability/eligibility/ptsd/) for PTSD:
>You may be eligible for disability compensation if you have symptoms related to a traumatic event (the “stressor”) or your experience with the stressor is related to the PTSD symptoms, and you meet both of these requirements.
>
>Both of these must be true:
>
>* The stressor happened during your service, and
>* A doctor has diagnosed you with PTSD

Other resources:
* [MST Claim Processing Requirements](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177469/M21-1-Part-VIII-Subpart-iv-Chapter-1-Section-B-Development-for-Posttraumatic-Stress-Disorder-PTSD-Claims-Related-to-Personal-Trauma)  
* [Evidence evaluation for PTSD claims for personal trauma](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177715/M21-1-Part-VIII-Subpart-iv-Chapter-1-Section-E-Evidence-Evaluation-and-Decisions-for-Posttraumatic-Stress-Disorder-PTSD-Claims-Related-to-Personal-Trauma)
* [Military sexual trauma and disability compensation](https://staging.va.gov/resources/military-sexual-trauma-and-disability-compensation/)

<hr/> 

### Traumatic Brain Injury (TBI)
> For use in identification and routing of TBI claims.

Note that there are many secondary conditions related to TBI. This implementation would only apply the special issue code to the TBI contention, and it would be on the veteran to provide evidence of condition and the claims processor to correlate other conditions to the TBI. See resources below for more info.

**Implementation**: Apply the special issue to a rated contention or new condition, if the contention details returns a contention with `"classificationType":9020` and `"claimantText":"traumatic brain injury (TBI)"` then the special issue can be added if it is not already on the contention.

Resources: 
* [TBI Special Issues](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000180832/M21-1-Part-V-Subpart-iii-Chapter-12-Section-B-Traumatic-Brain-Injury-TBI#1q)
* [Diagnostic Code 8045 Residuals of Traumatic Brain Injury](https://www.ecfr.gov/current/title-38/chapter-I/part-4/subpart-B/subject-group-ECFRab3ca55f4548afe/section-4.124a)

<hr/> 

### C-123 (C123)
>Apply to contentions for SC disability or death associated with Agent Orange exposure through regular and repeated duties flying on, or maintaining, contaminated former Operation Ranch Hand (ORH) C-123 aircraft. 
 >
>Reference:  For more information, see [M21-1, Part VIII, Subpart i, 1. A.2.a](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177422/M21-1-Part-VIII-Subpart-i-Chapter-1-Section-A-Developing-Claims-for-Service-Connection-SC-Based-on-Herbicide-Exposure).

This one will be difficult as it requires several pieces for a claim to be tagged both with the flash and the contentions related to Agent Orange exposure while serving. See [eligibility requirements for agent orange](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/). There are many conditions that are presumed caused by Agent Orange exposure, and there are several service requirements (when/where you were exposed). Specifically for C123 claims/conditions, the veteran must submit one or more of these forms:
* USAF Form 2096 (unit where you were assigned at the time of the training action)
* USAF Form 5 (aircraft flight duties)
* USAF Form 781 (aircraft maintenance duties)  
Additionally, C123 must also be applied as a flash to claims that claim conditions presumed caused by Agent Orange with exposure while serving in the USAF with duties on particular C-123 aircraft during service.

Implementation possibility: Veteran meeting time eligibility requirements based on service submits claim. Claim ID sent to app in VRO. When conditions are added to claim, any claim meeting presumptive condition has the special issue code added.


<hr/>

### Mustard Gas (MG)
>Use for all SC claims for disabilities resulting from exposure to mustard agents or lewisite not previously granted. 
>
>Reference: For more information, see [M21-1, Part VIII, Subpart iii, 3.A.2.b](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177452/M21-1-Part-VIII-Subpart-iii-Chapter-3-Section-A-Developing-Claims-for-Service-Connection-SC-for-Disabilities-Resulting-From-Exposure-to-Mustard-Gas-or-Lewisite).

Likely can't do. According to [VIII.iii.3.A.3.b.  Developing to the Claimant in Mustard Gas Claims](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177452/M21-1-Part-VIII-Subpart-iii-Chapter-3-Section-A-Developing-Claims-for-Service-Connection-SC-for-Disabilities-Resulting-From-Exposure-to-Mustard-Gas-or-Lewisite#3):
>The standard Section 5103 notice contained on [VA Form 21-526EZ, Application for Disability Compensation and Related Compensation Benefits](http://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf), is not sufficient for most mustard gas claims as it does not request the information needed to verify exposure to mustard gas or Lewisite.  In all claims based on such exposure, development to the claimant is required.

Additionally, even if a veteran has claimed a condition presumed caused by mustard gas (see [here](https://www.ecfr.gov/current/title-38/chapter-I/part-3/subpart-A/subject-group-ECFR39056aee4e9ff13/section-3.316)), it is still heavily dependent on if there is competant lay or medical evidence of that disability, along with the requirement of having obtained a Individual Exposure Summary/ILER response that documents the veteran as having had exposure. 

Implementation possibility: Veteran meeting time eligibility requirements based on service submits claim. Claim ID sent to app in VRO. When conditions are added to claim, any claim meeting presumptive condition has the special issue code added.

Resources:
* [Claims based on chronic effects of exposure to mustard gas and Lewisite](https://www.ecfr.gov/current/title-38/section-3.316)

<hr/>

### PACT (PACT)
>Use on any PACT Act related contention in accordance with the current PACT Act Implementation Standard Operating Procedure (SOP).
Depends on period / location of service:
>basic service and discharge requirements and any of these descriptions are true for you:
>* You served in the Vietnam War, the Gulf War, Iraq, Afghanistan, or any other combat zone after 9/11, or
>* You deployed in support of the Global War on Terror, or
>* You were exposed to toxins or other hazards during military service at home or abroad

Depends on if the condition is presumptive and related to service. 

Implementation possibility: Veteran meeting time eligibility requirements based on service submits claim. Claim ID sent to app in VRO. When conditions are added to claim, any claim meeting presumptive condition has the special issue code added.

Resources:
* [PACT Act and your VA Benefits](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) 
* [PACT Act Information Page](https://vbaw.vba.va.gov/bl/21/pact.htm)

### Fully Developed Claim (FDC)
>Apply to a single contention for FDCs submitted on one of the forms listed in [M21-1, Part X, Subpart i, 2.A.2.a](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177940/M21-1-Part-X-Subpart-i-Chapter-2-Section-A-General-Information-About-the-Fully-Developed-Claim-FDC-Program).

Intake process for FDCs require: 
>Identify a fully developed claim (FDC) by attaching the Fully Developed Claim special issue indicator to _at least one contention_ within the FDC claim. 

When submitting the 526EZ, the veteran must have selected "Yes, I have uploaded all my supporting documents" on the step **Fully developed claim program**.  
<img alt="FDC select" src="https://github.com/user-attachments/assets/427f66cf-a95c-48db-b143-46732443a71c" width="300"/>
If determined that other non-federal records are needed to make a decision on the claim, the claim will be removed from the Fully Developed Claims program and processed as a standard claim. If the veteran submits more docs on the claim or more info after submission it should be removed.
❓ Would we need to do this or would the claims processor notice and do this? 

Claims would be excluded from FDC based on a number of reasons outlined [here](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177941/M21-1-Part-X-Subpart-i-Chapter-2-Section-B-Processing-Fully-Developed-Claims-FDCs%3FarticleViewContext=article_view_related_article#2). Due to these complexities, it should likely be left to the claims processor to evaluate wether or not the claim qualifies for FDC at claim establishment. 
❓ Should we add the special issue to contentions and let it be routed and allow the claims processor to determine that it should be excluded and remove them? 
❓ There are also special issue codes related to these exclusions that are outlined [here](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177941/M21-1-Part-X-Subpart-i-Chapter-2-Section-B-Processing-Fully-Developed-Claims-FDCs%3FarticleViewContext=article_view_related_article#2e), maybe some of them could be applied as well? 

Implementation: Since the application of this special issue would have to occur based on the form data, we would need to send the claim ID to an app within VRO and wait for the contentions to be added to the claim, then the special issue could be added to the claim via BIP Claims API.

Resources:
* [M21-1, Part X, Subpart i, Chapter 2, Section A - General Information About the Fully Developed Claim (FDC) Program
](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000177940/M21-1-Part-X-Subpart-i-Chapter-2-Section-A-General-Information-About-the-Fully-Developed-Claim-FDC-Program)
* [Fully Developed Claims](https://www.va.gov/disability/how-to-file-claim/evidence-needed/fully-developed-claims)

<hr/>

### Standard Processing Claim
This special issue is not included in the list of [special issues](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000179710/Appendix-E-Index-of-Corporate-Flashes-and-Special-Issues%3FarticleViewContext=article_view_related_article#2).

<hr/>

**Comment by dfitchett** [comment]
Sequence / Process Flow diagrams created in [mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1727297726171/6a772263c4577f5697c52cf7eb2055d76e426833?sender=u144b768a106b68952f414031).
