### ISSUE TITLE
Staging POC/testing of writing ALS flash

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3667]
- Given the initial work on ALS flash...
- HMW create a quick POC and validate that it works in VBMS?
  - We should be able to do this in va.gov staging and VBMS UAT. Find a vet in staging/UAT. Should be easier than before because we needed existing ratings. Just need to send in a new claim for ALS, then we should be able to verify that works. We may be able to use Dianne B. Scott!
  - Derek has been using Nathan Jolly to create Vet claims for us.

**Comment by dfitchett** [comment]
Due to the complex nature of getting a user already rated for ALS, and the simple logic in the code that handles that case, we are skipping that [scenario](https://docs.google.com/spreadsheets/d/1xqy8Rp78RjumxYqEAMoqEOKYxUgsosDqtXcwccZ3ApQ/edit?gid=0#gid=0&range=13:13) and calling the tests complete.
