### ISSUE TITLE
On call for VRO

### ISSUE THREAD

**Issue by meganhicks** [department-of-veterans-affairs/abd-vro#3736]
# Responsibilities for the primary on-call engineer:

- [x] Monitor the#benefits-vro-alerts channel for alerts triggered through datadog. For any incidents which impact partner team applications, please follow the issue triage procedure below.
- [x] Monitor #benefits-vro-support for potential incidents
- [x] Monitor SecRel
- [x] Monitor Dependabot
- [x] Give Delivery Manager the MTTR to post in the Sprint Review Deck

# Issue Triage Procedure

- Upon receiving a notification, promptly evaluate the severity of the incident and perform triage accordingly.
- Collect pertinent information related to the triggered alert(s), with a focus on communicating the impact and, if possible, identifying the root cause. Notify all relevant parties, including LHDI or partner teams, about the observed behavior, and create a corresponding ticket for the issue.
- If the issue is considered straightforward to fix, proceed to address it. Notify the team and bring a user story into the current sprint to represent the work.
- For issues deemed complex and requiring more discussion, create a ticket and collaborate with the PM to prioritize it effectively.
- Maintain transparent and frequent communication with the team and partners through the support channel, especially if the issues hinder their ability to deploy or use applications appropriately.
- Document the findings and issues created in a wiki page under the homepage under the heading "Partner Teams" subheading "Partner Team Incident Reports"

**See also:** wiki page for [Incident Response](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response).

# Secondary responsibilities

- Remain accessible to the primary for assistance as required, and concentrate on addressing smaller tickets or collaborating on larger ones during the Sprint.

**Comment by BerniXiongA6** [comment]
@BerniXiongA6 will follow up on Slack to get confirmation on who can do on-call

**Comment by BerniXiongA6** [comment]
@gabezurita is Primary
@brostk is Secondary

Code freeze for VA.gov occurs 11/28-29.

Per VRO Enablement, OK to have no on-call coverage from 11/28-29 and limited coverage adjacent to this timeframe. Gabe and Kyle have agreed that they could offer very limited coverage on 11/27 (in case of severe VRO platform emergencies) given that VRO will have no available engineers for regular on-call coverage that day due to holiday/PTO schedules.

**Comment by BerniXiongA6** [comment]
Here's a final draft of the Limited Coverage Slack message we'll share with partner teams ahead of next week's holiday schedule (thanks Bianca, Kyle, Gabe):

---
@conditions-team @employee-exp-team

ANNOUNCEMENT
Limited VRO On-Call Coverage During Thanksgiving (11/27-29)

In observance of the Thanksgiving holiday, please note the following adjustments to the VRO team's on-call support schedule:

Wednesday, November 27
- On-call support will be available for [SEV 1 (Critical)](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Incident-Response#step-1-triage) issues only.

Thursday, November 28 and Friday, November 29
- On-call support will be unavailable due to the [VA.gov](http://va.gov/) code freeze.

All non-critical incidents reported using the 
['Report a VRO incident'](https://slack.com/shortcuts/Ft07BZKNEZ9S/35ced244dde8f7953ddef1fccd01bc26)
 workflow during these days will be addressed on Monday, December 2, when normal support hours resume.

If you have any questions or concerns, please reply to this thread and we will respond as soon as possible.
Thank you for your understanding and cooperation.

---

cc: @bianca-rivera @meganhicks @amylai-va @brostk @gabezurita

**Comment by BerniXiongA6** [comment]
Hi @gabezurita @brostk could you tick the checkboxes on the AC of this ticket if they're completed and then close this ticket since Sprint 6 is over? Any follow up tasks, you could create new tickets to add to Sprint 7. Thank you!
