### ISSUE TITLE
(EE) Inform NWQ of EP Merge Shutdown [DISCUSSION TRACKING]

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3754]
Notify NWQ partners of the impending shutdown of the EP Merge application.

**Comment by mackhowell-nava** [comment]
We discussed in [EE Team Sync today](https://docs.google.com/document/d/13UOIuUE1i6gTMWG4YbKl1esuy93c8IhLFwvmyl92LmE/edit?tab=t.0#heading=h.9tifs7n0dddq):


Updates on EP Merge shutdown decision pending

- Jen / NWQ discussing still… the app remains operational
- Josh estimated ~100 VSR hours saved per month
- EE / VRO enablement to discuss further today
- Cory scheduling meeting with VA Platform team to discuss migration possibilities and feasibility (Wednesday)
   - Derek to be invited to Wed call to consult on this
- Derek – ep merge app is more complex to migrate than other apps due to rabbitmq usage
   - Will need to convert rabbitmq clients to REST clients.
   - BGS soap service integration is the main technical challenge
   - BIP claims API transition should be straightforward
