### ISSUE TITLE
Evaluate some of the tricker overflow design updates

### ISSUE THREAD

**Issue by mackhowell-nava** [department-of-veterans-affairs/abd-vro#3783]
Follow up to: https://github.com/department-of-veterans-affairs/abd-vro/issues/3709

See [comment](https://github.com/department-of-veterans-affairs/abd-vro/issues/3709#issuecomment-2486343603):

> Sometimes a list-and-loop affects only a subset of the questions in a section (e.g. 5D through 5G). How is this captured by the key?
> **Action item:** investigate.

> One of the proposed overflow page improvements is to group questions by section. Section data is not currently included in the key, but it seems straightforward enough to add that as one more attribute on each field.
> **Action item:** investigate feasibility of this.

> Another formatting improvement is to layout list-and-loop responses in a more tabular way.
> **Action item:** investigate the feasibility of structuring the overflow data this way, as well as the feasibility of a tabular layout in prawn-markup.

**Comment by nanotone** [comment]
## PDF form key deep dive

The form KEY (all-caps for disambiguation) configures how form data gets filled into a PDF template, how fields overflow, and how overflowed values show up on the overflow page.

For starters, some terminology:
- scalar: a single atomic value (e.g. the string `"Smith"` or date-string `"2001-01-01"` or boolean value `true`)
- array: an ordered list of values
- hash: an unordered key-value mapping

The form KEY is a nested hash whose hierarchical structure mirrors that of the form data JSON received from the frontend. Hash keys mapping to nested hashes in the KEY will correspond to hash keys in the input. For example, if the input data has a nested field like `data["bankAccount"]["routingNumber"]` then that nesting is also where this field's configuration lives in the KEY.

The flexibility and power of the KEY lies in how it deviates from a purely 1-to-1 mirroring of the input data.

### Initial data transformation

Technically, the configuration in the KEY doesn't truly apply to the JSON data from the frontend. There's an initial data transformation step described in a `merge_fields` method accompanying every KEY. This performs basic changes like splitting a 9-digit SSN (a scalar) into the 3 labeled parts (a hash). Some of these operations are so common that they've been collected into a shared library.

Generally, the `merge_fields` step can perform extensive changes to the input data structure, but none that affect the actual information captured in the form submission.

### Arrays are implicit

The KEY never explicitly specifies which fields contain an array of values, e.g. resulting from a list-and-loop. This means any field could potentially have an extra layer of multiplicity, which makes reading a KEY somewhat less straightforward. But in practice, it's pretty easy to tell:

```ruby
'dependents' => {
  limit: 3,
  'fullName' => {
    'first' => { ... },
    'middle' => { ... },
    'last' => { ... }
  }
},
```

In this example, `dependents` would obviously map to a list of objects, as it wouldn't make sense for all of a Veteran's dependents to be captured in a single nested object. On the other hand, each of those arrayed objects would just map `fullName` to a simple nested hash of 3 scalars.

The giveaway here is that there is always a special `limit` attribute. This is due to the practical consideration that no PDF template can support arbitrarily many dependents; there is always a maximum before triggering the overflow page. The next section explains these special metadata attributes.

### Metadata attributes

Apart from hash keys that mirror the names of nested objects in the input data, config objects in the KEY can have a number of special attributes that determine behavior during PDF generation:

- `always_overflow`: Always send to overflow. For arrays, this also omits the index.
- `dollar`: Prepend $ when overflowing.
- `first_key`: In an array-of-hashes, this hash key identifies the field that gets the "See add'l info" when overflowing
- `format`: Only observed value is `date` which specifies a date field.
- `key`: Name of the fillable field in the PDF template. May contain an iterator wildcard which allows filling in multiples in a list-and-loop.
- `limit`: Maximum array size or string length.
- `question_num`: e.g. `3` or `7.1`
- `question_suffix`: e.g. `A` or `[Veteran]`
- `question_text`: e.g. `Other first name` or `(2) HOW DID YOUR PREVIOUS MARRIAGE END?`
- `skip_index`: Always omit index in overflow page question label. I can't find any instances or motivation for this.

Again, the `limit` attribute does a lot of heavy lifting in determining how to overflow. In array context, the limit specifies how *many* fields exist in the template for a complex question like "list all your dependents." In scalar context, the limit specifies how *wide* a single field is in terms of accommodating some number of characters. Of course, both contexts are seen within a single question -- e.g. a list of dependents overflows when there are too many to fit, or when one has a name that's too long to fit.

**Comment by nanotone** [comment]
## Comments on the HashConverter class

`PdfFill::HashConverter` is the main class that performs all the tricky logic of determining what gets filled into a PDF template and what gets written to the overflow page. Because of the nested nature of the form KEY, HashConverter is somewhat abstract, with its most important methods recursively calling each other as the code walks through a form "tree." In contrast, `PdfFill::ExtrasGenerator`, which actually does the generating, is very concrete and deals with nitty-gritty issues of visual rendering.

This is the documentation I jotted down about HashConverter while wrapping my head around the form KEY's structure (which I wish were comments in the code). It's primarily aimed at engineers.

**But, of consequence to overflow design**: The only way to add content to the overflow page is by calling `ExtrasGenerator#add_to_extras` with a scalar value and a question metadata object (for the label). ExtrasGenerator does not explicitly admit any higher-order data structures. This means tabular-formatted data will require cleverness, rewriting, or both.

- `transform_data`
  - The main entrypoint to HashConverter, called from `PdfFill::Filler#process_form`
  - Takes in a form input object and the corresponding config object in the KEY.
  - Walks through the form input object and figures out what data needs to be added to overflow.
  - Returns a new hash representing what gets plugged into the PDF template.
- `transform_array`
  - Takes in an array of form input objects and the corresponding config object in the KEY.
  - Performs all the overflow determination logic for the array.
- `check_for_overflow`
  - Same arguments as `transform_array`
  - Returns whether an array of values (scalar or hash) will overflow.
- `add_array_to_extras`
  - Same arguments as `transform_array`
  - Adds an array of values (scalar or hashes) to overflow.
- `set_value`
  - Takes in a form input scalar, the corresponding config object in the KEY, and the index if it was part of an array.
  - Optional argument: whether the scalar value is already the result of an array overflow.
  - Sets a scalar value to be filled into a field in the PDF template, possibly adding it to overflow.
- `add_to_extras`
  - Same required arguments as `set_value`
  - Adds a single mapping (from question metadata to scalar value) to overflow.
- `convert_value`
  - Same required arguments as `set_value`
  - Converts a value to a scalar string
- `overflow?`
  - Same required and optional arguments as `set_value`
  - Return whether a scalar value will overflow. If the value is already the result of an overflow, it will not trigger overflow again; this is how `See add'l info` just gets truncated when it's filled into a PDF template.

**Comment by nanotone** [comment]
## Answers to overflow page re-design investigation

We now have the machinery to provide answers to what originally seemed like fairly innocuous questions about the overflow page.

### How to identify which set of questions belongs in a table and which don’t

The form KEY is not actually aware of sets of related questions; its structure is engineered to fit that of the form input data. The grouping of fields that comprise parts of a question is done by assigning `questi
on_num` and `question_suffix` metadata accordingly, as that's how fields are sorted in the overflow page. So a list-and-loop that affects sub-questions 5D through 5G would just be an array containing hashes with `question_num` 5 and `question_suffix` from D to G.

### How to add section names and group questions under them

ExtrasGenerator, the class that actually renders text to overflow, has no concept of larger groupings than individual (sub-)questions and their scalar values. But it should be possible to add a new metadata attribute, say `question_section`, that affects the question sorting at the highest level. A couple issues would need to be addressed:
- `question_num` and `question_suffix` are configured explicitly on every field, but if we follow suit with `question_section` it may impose excessive boilerplate on the form KEY. On the other hand, would implicitly inheriting `question_section` via the form KEY hierarchy be too perilous (c.f. CSS)?
- In a world with question sections, what should happen to questions without a section?

### When a question has multiple sub-fields, do we show only the overflowed fields or all the fields?

There is some flexibility of implementation here, but from my understanding, the behavior for scalar overflows is to add only overflowed fields to the overflow page. This goes back to the fact that the sub-fields are not strongly grouped together in the form KEY.

### Feasibility of a tabular layout for list-and-loop responses

As mentioned in the above comment about HashConverter and ExtrasGenerator, the absence of any higher-order organization of fields makes this quite tricky. The ExtrasGenerator essentially handles one question/response pair at a time.

At first glance, it would seem that we might be able to use the question *index*, which is the one piece of question label metadata that is auto-generated (recall that `question_num` and `question_suffix` are explicitly set). The *index* is responsible for the "Line {x}" text. The challenge lies in
- adding a way to configure tabular data in the form KEY,
- adding machinery to ExtrasGenerator to treat indexed responses differently, and
- somehow connecting those dots. The current interface between HashConverter and ExtrasGenerator is extremely simplistic.
