### ISSUE TITLE
Move Max CFI to a new repo

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/abd-vro#3830]
The Max CFI api needs to be moved to a new repository under the Department of the VA Github. 

Acceptance Criteria:
- [x] Public Repo named `disability-max-ratings-api`
- [x] Migrate the [ee-max-cfi-app](https://github.com/department-of-veterans-affairs/abd-vro/tree/develop/domain-ee/ee-max-cfi-app), preserving git history of that subdirectory
- [x] #3835 (split off, not completed as part of this issue)
- [x]  Add a license (choosing correct one)
- [x]  Give VRO Team access 
- [x]  Add github files:  
   - [x]  CODEOWNERS
   - [x]  .gitignore
   - [x]  dependabot
   - [x]  [.emass-repo-ignore](https://github.com/department-of-veterans-affairs/va-abd-rrd-argocd-applications-vault/blob/main/.github/.emass-repo-ignore)

**Comment by gabezurita** [comment]
Here's the repo!
https://github.com/department-of-veterans-affairs/disability-max-ratings-api

**Comment by gabezurita** [comment]
I added a few AC:
- Choose the correct license
- Give VRO Team access 

I noticed [vets-api uses Creative Commons Zero Universal](https://github.com/department-of-veterans-affairs/vets-api/blob/master/LICENSE.md), so I chose the generic version of it when initiating the repo. We may need to update it.

I gave the VRO Team access.

**Comment by gabezurita** [comment]
@dfitchett, I'm adding 1 more AC around migrating git history:
- [ ] Migrate the [ee-max-cfi-app](https://github.com/department-of-veterans-affairs/abd-vro/tree/develop/domain-ee/ee-max-cfi-app), preserving git history of that subdirectory

Thinking that there is value in preserving max-cfi-specific git history. Here are some alternatives (I'm leaning towards **Option 3**, `git subtree split`, so `git subtree split --prefix=domain-ee/ee-max-cfi-app -b disability-max-ratings-api-init`):

### Option 1: **Copy the files (lose Git history)**
- **Advantages:**
  - Simple and quick.
  - Results in a clean Git history for the new repository.
- **Disadvantages:**
  - Loses the historical context of changes.
  - Makes debugging or understanding past changes harder.

### Option 2: **Fork the old repo and delete unnecessary files (retain history, but with noise)**
- **Advantages:**
  - Keeps all history intact, making it easier to trace back the lineage of files.
  - Preserves the integrity of the original commits related to the service.
- **Disadvantages:**
  - The new repo’s history will include irrelevant commits, which could make it harder to work with.
  - Can cause confusion for developers due to unrelated historical context.

### Option 3: **Use `git filter-repo` or `git subtree split` to extract relevant history**
This is a more precise approach that avoids the drawbacks of the above options.
1. Use `git filter-repo` (recommended) or `git subtree split` to extract the service’s files and related commit history from the monorepo.
2. Push the extracted history to a new repository.

#### Steps for `git filter-repo`:
   1. Clone the monorepo locally.
   2. Use `git filter-repo` to rewrite the history:
      ```bash
      git clone --no-hardlinks <monorepo> <new-repo>
      cd <new-repo>
      git filter-repo --path <path-to-service> --path-rename <path-to-service/>:/
      ```
   3. Push the resulting repository to a new remote.
   4. The new repository will contain only the commits relevant to the service.

#### Steps for `git subtree split`:
   1. Use `git subtree split` to extract the service:
      ```bash
      git subtree split --prefix=<path-to-service> -b <new-branch-name>
      ```
   2. Create a new repository and push the split branch:
      ```bash
      mkdir <new-repo>
      cd <new-repo>
      git init
      git pull <monorepo> <new-branch-name>
      ```

- **Advantages:**
  - Keeps the relevant history without irrelevant noise.
  - Results in a clean new repository tailored to the service.
- **Disadvantages:**
  - Slightly more complex process.
  - Requires tools like `git filter-repo` or careful handling of `git subtree`.

### Option 4: **Hybrid approach**
- Fork the repo to retain history, then periodically prune irrelevant commits (e.g., using `git filter-repo` later for cleanup).
- Useful if you want to migrate quickly and refine history later.

### Recommendation:
If preserving history is critical and you want a clean result, **Option 3 (using `git filter-repo`)** is the best choice. It’s relatively straightforward and produces a clean repository with only relevant commits.

If you prioritize speed or don’t need history, go with **Option 1**.

Would you like assistance with the commands or detailed guidance for any of these methods?

**Comment by gabezurita** [comment]
This is still a WIP, but I’ve migrated max-cfi from the abd-vro monorepo to its own service repository while preserving the subdirectory’s Git history using git subtree split --prefix=domain-ee/ee-max-cfi-app -b disability-max-ratings-api-init (and a handful of other operations) :tada:
You can check out the migrated files/commits here:
https://github.com/department-of-veterans-affairs/disability-max-ratings-api/commits/main

**Comment by gabezurita** [comment]
@dfitchett, I'm splitting off the rename to a separate issue to keep this change scoped!
https://github.com/department-of-veterans-affairs/abd-vro/issues/3835
