### ISSUE TITLE
Begin process to establish and test connectivity to BAM shared services for BGS claim update capabilities

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#388]
**User Story**

Work with our BAM points of contact to follow their process for establishing and testing shared services connectivity for VRO, so that VRO can access the shared services for claim update functionality. Document any parts of the process that would be beneficial to have documented in future. 

**Acceptance Criteria**

1. Process of establishing and testing BAM shared services connectivity is underway and being tracked towards completion.
2. Documentation has been created in cases where it has future value. (Up to engineers' discretion what those cases are)

**Not included in this work**

This ticket is just for connectivity, and does not include any of the development to use the shared services. 

**Notes about work**
See email thread that Premal opened with BAM points of contact. [Slack thread](https://dsva.slack.com/archives/C03JRKKD11B/p1663864482976239) for reference.

**Comment by yoomlam** [comment]
Add findings to [Integrations: BAM Shared Services](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Integrations%3A-BAM-Shared-Services), linked from https://github.com/department-of-veterans-affairs/abd-vro/wiki/External-APIs#bam-shared-services

**Comment by ENeal49** [comment]
blocked - submitted for access

**Comment by amprokop** [comment]
We received the credentials for DEV and UAT environments on Friday afternoon.

@cweagans and I were able to test out the BIP Claims API in the Dev environment using their swagger page.

Using Chrome to inspect requests and responses, we were successfully able to:

- Add "RRD" as a special issue on the claim
- Change the temporary station of jurisdiction on the claim to 398
- Mark the claim as RFD

We were not yet successfully able to test the credentials we were given from BIP, as it turns out the Swagger page connects to an environment that does not require those credentials. However, at this point I think we have enough knowledge of the API that I'd strongly recommend using it over BGS.

**Comment by amprokop** [comment]
Marking this issue as "Ready for Review" so we can have a quick team discussion, but I think we should have the all clear to move towards implementation.
