### ISSUE TITLE
Check fast-tracking eligibility for presumptive claims

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#446]
**User Story**

VRO needs to check if a presumptive claim is eligible for fast-tracking.

Requires integration: No, flash info will be provided by MAS (VBAAP) when notifying VRO about automation eligible claims.

**Acceptance Criteria**

1. After the `inScope?` check (described in #428), VRO checks if a claim is `disabilityActionType == "NEW"` and has the relevant Veteran "flash" (i.e., `Agent Orange Exposure Verified` flash (ID: `266`)). If it does, add a new `presumptive = true` field to the claim that is passed to the `AssessData_Route`.
   - The DB should model/store `disabilityActionType` on the claim.
   - The DB should model the flashes associated with the Veteran. This is a list of integers.
2. Offramping ([see linked diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1653424407090/46c1aff7e984db50fc9a436b5f647199b31f14a8?wid=51-1672177398500)): 
   - If the `disabilityActionType==NEW` and the flashID is not present or not equal to `266`, then off ramp the claim with `offrampReason=newClaimMissingFlash266`
   - If `disabilityActionType==INCREASE` (ignore the flash), send claim to the `AssessData_Route`. Do NOT offramp.
3. Within the `AssessData_Route`, the `SaveAssessment` step saves `presumptive = true` on the claim DB record for presumptive claims. This allows the health data assessor (or other future data assessor that considers the Veteran's service history) to determine the value of `presumptive` on the claim DB record without having to reassess the logic that determines if a claim is eligible for VRO's presumptive processing (which will change as we add more VRO capabilities).

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**
- For traceability: this user story corresponds to:
   - "VRO adds logic to check against Veteran flash for presumptive eligibility"

**Comment by dianagriffin** [comment]
@yoomlam May be worth noting that these would be single issue new claims that have a disability classification code of 3460 (hypertension) or 3370 (high blood pressure)? Source [thread](https://dsva.slack.com/archives/C03JRKKD11B/p1664483015522799?thread_ts=1664479085.080659&cid=C03JRKKD11B)

**Comment by yoomlam** [comment]
Checking the `disabilityClassificationCode: 3460 (hypertension) and 3370 (high blood pressure)` will already be implemented for #428.

**Comment by emilytheis** [comment]
Small learning re: @dianagriffin and @nanotone comment is that these two classification codes (3460 and 3370) are old, deprecated codes that are really only used by va.gov, and being rejected by VBMS and not used by VBA. So going forward we shouldn't use them as cornerstones of our logic. 

The way one would identify new hypertension claims would be those with a contention name of "Hypertension" or "high blood pressure." I am working with another team to ensure those are classified with the correct, up-to-date classification of "979 (Hearts, Veins, Arteries). That classification code is too generic of a filter to identify hypertension claims, since it is also used for many other heart conditions. 

This is a little bit tricker because contention names can be anything. Since MAS is actually doing the identifying of which claims are eligible from both the mail portal and va.gov, I think this doesn't really affect our decisions now. But those classification codes are not the way MAS would be identifying them.

**Comment by ENeal49** [comment]
Per Rajesh Krishnasamy with Amida, ticket can be closed since he doesn't have access to Github.

**Comment by amylai-nava** [comment]
Re-opened to track bullet point 2 in the AC. See [slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1674157324050269?thread_ts=1674066947.858829&cid=C01Q7979Z7D) for discussion. cc: @rajesh-Krishnasamy
