### ISSUE TITLE
Conduct VRO robustness testing

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/abd-vro#527]
VRO consists of several containers. We should test if VRO can recover if a container (1) shuts down and (2) has an error but doesn't shut down. This should be tested with each container and with multiple containers to test the recovery limits of VRO.

- Create issues like [#243 Python microservices shut down when RabbitMQ shuts down](https://github.com/department-of-veterans-affairs/abd-vro/issues/243)
- Review https://hevodata.com/learn/rabbitmq-durable/ and configure RabbitMQ, e.g. `PERSISTENT_DELIVERY_MODE ` and `prefetch_count=1`.

**Comment by yoomlam** [comment]
This ticket doesn't require experience with the codebase. The assignee should know how to start VRO locally and use Docker.

**Comment by dianagriffin** [comment]
@yoomlam Bumping this to Sprint J. At this point, should it still be considered low-priority, or do we need to get to it sooner rather than later?

**Comment by yoomlam** [comment]
@dianagriffin Related tickets #243 and #565 should probably be done before this ticket, since they can inform the testing needed for this more general ticket.

**Comment by yoomlam** [comment]
[Another finding](https://github.com/department-of-veterans-affairs/abd-vro/issues/565#issuecomment-1345370701) -- please verify. For each finding, create a ticket that includes how to reproduce the problem.
Notify Amida of the ticket in #benefits-virtual-regional-office and see if/when they can work on the ticket.

**Comment by sethdarragile6** [comment]
A check-in here. To say progress has been slow on this ticket is an understatement. SecRel work has been winning the competition for my attention in the past few weeks, and the remaining time has been spent trying to grok the related work in the comments + trying to decide how to best organize this endeavor.

On that last point, I did have some early thoughts that. This whole idea of trying to test the resilience of multiple interacting containers given various conditions reminded me of a concept I'd read about ages ago called "chaos engineering". In chaos engineering, you purposely seed your container environment with bad data, throw too much data at it, tear down various containers, etc- all with the purpose of testing the resilience of your infrastructure. At the time, I had to laugh at it, because it seemed counterintuitive (or even counterproductive) to purposely try to sabotage your production environment.

I would still be reluctant to apply these principle to a production environment. However, this seems to me to be a fabulous idea in lower environments- particularly your local dev environments where the risks are the most minimal. So I started googling around a bit and found that chaos engineering was alive and well out there. Based on [this list](https://www.harness.io/blog/chaos-engineering-tools) of top chaos engineering tools, I started to look at a tool called [Chaos Mesh](https://chaos-mesh.org/docs/quick-start/)  and started down the road of installing all of its many prerequisites (and _their_ prerequisites, ugh). I got about 90% there in an afternoon or two. However, since I am not a devops guy and have never used kubernetes before- I had much a much greater learning curve for this than I realized. So I put this on the backburner and set out to try and do this ticket's work manually, as intended.

I still think, however, that this tool (or something like it) could be a useful tool for our project. This is really my first "microservices" project, but I feel like a tool like this could be very valuable. Unit tests, integration tests, end to end tests are all needed to test various slices of code interactions. But a tool like this could be helpful in tying in ALL containers in your environment, and perhaps better automate a matrix of all possible interactions system wide.

Thoughts? @yoomlam @ahay-agile6

**Comment by yoomlam** [comment]
Quick response: I think those ideas have potential for the long term, and I anticipate a good amount of effort to set it up.

For this ticket, I was thinking some quick manual testing to identify problems that Amida could tackle before they offramp.

**Comment by sethdarragile6** [comment]
I found another problem with resiliency when restarting rabbitmq. I'll write up a ticket. Quick details:

1. When stopping the rabbitmq container, swagger call (/v1/full-health-data-assessment with "diagnosticCode": "7101") just spins forever, and the logs in each container keep filling up with errors about not finding rabbitmq
2. After bringing rabbitmq back, resubmitting the swagger call continues to spin forever. 
3. Only after restarting the app-1 container, resubmitting the swagger call succeeds

**Comment by sethdarragile6** [comment]
⬆️ update on the above. I have not been able to reproduce the issue as described above, for whatever reason. If I allow the swagger call to spin for a long period of time (~15 minutes or more), I do find that app-1 is _slow_ to recover. After cancelling the call (which doesn't actually seem to happen on its own- I have to simply refresh the page to start over), the next call will go out and eventually return an error message in the json response after a 1-3 minutes (which is better than simply spinning forever, perhaps). But the _next_ call I make is successful. So recovery is happening here, but perhaps not as quickly as we would like.

I've completed a testing matrix of container interactions over the `/v1/full-health-data-assessment` and `/v1/evidence` endpoints, which I believe touches all relevant containers (skipping the feature toggle container, as it is not in use yet). I'll be documenting that testing matrix, perhaps producing a diagram of container interactions, and generating 2 tickets: 1 to address this infinite hang upon calling the endpoints when rabbitmq is down, and 1 to address the persistent error state that occurs when the `svc-lighthouse-api-1` is restarted

**Comment by sethdarragile6** [comment]
Testing matrix for this effort:

https://docs.google.com/spreadsheets/d/1H_gs10cGbwdWaMXEiO-cXvOzlEanh1wmNkNWMPcbdgQ/edit?usp=sharing

**Comment by yoomlam** [comment]
I had this in my notes and didn't noticed the error message in your spreadsheet:
```
Context: restarting postgres; app no longer writes to DB and logs no errors
- Error message to investigate: `g.va.vro.service.db.SaveToDbServiceImpl  : Could not find claim by claimSubmissionId, exiting.`
```
