### ISSUE TITLE
Test Lighthouse Veteran Verification API for retrieval of Veteran flashes

### ISSUE THREAD

**Issue by dianagriffin** [department-of-veterans-affairs/abd-vro#591]
**User Story**

RRD automation in the VRO needs to be able to run logic that checks for Veteran flashes relevant to the PACT Act cohorts, e.g. `Agent Orange Exposure Verified` (flash ID: `266`), so that it can identify potentially presumptive claims and process them through RRD automation. 

The LH Veteran Verification V2 API includes the ability to query Veteran flashes, and is now available in the LH sandbox environment. We want to test retrieving Veteran flash from this API for future use in VRO. 
- Note that this is **not** a requirement for VRO iMVP because MAS will include Veteran flash data when it notifies VRO of a claim, although nothing prevents it being included in iMVP if development capacity and testing timelines permit. 

See this [slack thread](https://lighthouseva.slack.com/archives/CDW40SBTL/p1665523120451529) for API documentation as well as instructions on accessing the Vet Verification API in the sandbox environment. 

**Acceptance Criteria**

1. Veteran Verification V2 API has been tested to confirm we can retrieve the Veteran flashes VRO needs for presumptive eligibility logic (see #446)
2. Any issues or feedback from testing the API has been shared back to Nichole Harris (using [this thread](https://lighthouseva.slack.com/archives/CDW40SBTL/p1665523120451529) or starting a new thread in #api-vet-verification)

**Not included in this work**

Implementation of VRO integration with this API is not included in the scope of this ticket.

**Notes about work**
#446 implements the logic that will check Veteran flash (agnostic of VRO's data source for Veteran flashes)

**Comment by nanotone** [comment]
I was able to successfully hit the VV (version 2) API in sandbox, and will include some breadcrumbs here in case anybody else wants to follow along. This is a rather verbose retelling of other documentation, which I figure could be useful for someone new to the CCG and JWT procedure.

## Setting up credentials

- Follow the instructions in Nichole's `CCG OAUTH INSTRUCTIONS_VV V2.doc` to generate an RSA public/private key pair.
  - Yes, the easiest way to convert it into JSON form is https://russelldavies.github.io/jwk-creator/ -- what a great public service.
- Paste the public key in the [request for sandbox credentials](https://developer.va.gov/onboarding/request-sandbox-access) and under Client Credentials Grant APIs, select Patient Health API. There is no actual option for VV API, so just mention it in the text box.
- Receive an email with an OAuth Client ID; this should be instantaneous. Then, notify the VV API team to [manually map this Client ID to an authorization policy](https://lighthouseva.slack.com/archives/CDW40SBTL/p1667316392734619?thread_ts=1667313006.604639&cid=CDW40SBTL) -- at time of writing, there is no automated process for this. Without this step, you'll be denied an access token.

## Fetching an access token

Using a JWT tool of your choice (I used [PyJWT](https://pyjwt.readthedocs.io/en/stable/)), follow the instructions in `CCG OAUTH INSTRUCTIONS_VV V2.doc` to construct an access token request.
- The JWT contains a JSON payload (required fields: `aud`, `iss`, `sub`, `exp`) signed with the private key. Use https://jwt.io/ to verify that the signing works and can be validated by the public key.
- Make a POST request to the [access token endpoint](https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/token) with the required form data. In addition to the `grant_type` and `client_assertion_type` values provided in the doc, take note of the following values:
  - `client_assertion` should be the signed JWT
  - `scope` should be `launch flashes.read` although we may eventually want something like `launch veteran_status.read flashes.read`
  - `launch` should be the base64-encoded `{"patient": "1234567890V123456"}` except with the ICN of one of [these test accounts](https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts/verification_test_accounts.md)
- The response is a JSON object with an `access_token` key. Keep this key for the next step.

## Calling the flashes endpoint

Within the access key expiration window (appears to be 10 minutes by default), make a GET request to https://sandbox-api.va.gov/services/veteran_verification/v2/flashes
- Include an `Authorization` HTTP header with value `Bearer YOUR_ACCESS_TOKEN`. This is the only way to specify which veteran we want, since the endpoint doesn't accept any parameters.

At time of writing, a successful call to the flashes endpoint will return a JSON response that looks something like
```json
{
  "flashes": [
    {"flashName": "Agent Orange (AO) Exposure Verified"},
    {"flashName": "Gulf War or Post-9/11"}
  ]
}
```

## Further work

@dianagriffin Are we still working with our partners on the data side to get a numeric code for these flashes? And what are next steps?

I know that as a prerequisite for getting into production, we (you?) have to fill out this [production access form](https://developer.va.gov/onboarding/production-access-application), and once submitted Premal can help streamline the process.

**Comment by dianagriffin** [comment]
@nanotone Based on the sample response you included + your question about getting a numeric code, I'm assuming that this API currently doesn't return the numeric code? 

@amylai-nava You know more about the flashes than I do -- do you have a sense of whether we need the numeric code for our presumptive use case? (I'm assuming it would be good to have, but wondering if it's must-have). For context, this ticket was to test the new LH Veteran Verification V2 API to pull Veteran flashes, which is our preferred long-term solution for getting the flashes, although in the short-term (iMVP) we will get them directly from MAS.

**Comment by dianagriffin** [comment]
Closing this ticket as the testing is done; next steps will be back on product to determine priority on pushing ahead on implementation.

**Comment by amylai-nava** [comment]
@dianagriffin my thought is that having the numeric code is a must have, not because of the presumptive use case per se, but for the reasons you're probably thinking about (more reliable in case the flash name changes, etc.)

**Comment by dianagriffin** [comment]
@amylai-nava Thanks, that's helpful! Sounds like feedback we can share back to the VV API team; I'll mention to Premal
