### ISSUE TITLE
Next-gen design: Decide on 2-column vs. 1-column design

### ISSUE THREAD

**Issue by KimLadin** [department-of-veterans-affairs/abd-vro#792]

**Comment by carodew** [comment]
I don't think I should be assigned to this ticket since I'm not driving it forward it anyway, so I'm going to take myself off bc I find it distracting in my list of things I need to do. That doesn't mean I'm not willing to participate in relevant discussions.

**Comment by lydiahooper** [comment]
We decided to keep the two column layout on the cover page and last page of the next gen prototype, and to accept the guidance to help screen magnifier users find the content on the right side of the page. We added to the content on the left side of the cover page text that lets readers know there is content on the right. We didn't feel this was necessary for the last page since there is already paragraph text that spans across the entire page.
