### ISSUE TITLE
Feature toggle service java app connection

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/abd-vro#802]
**User Story**

As a developer, I want the app to connect to the feature flag microservice, so that feature flags can be used to gate code.

**Acceptance Criteria**
- The app will listen to Redis for changes to a Redis key.
- The app will track the last timestamp it updated the feature flags. We can invalidate or force a hash refresh by setting the timestamp to null.
- Upon app startup (probably after a few seconds delay), the app queries the service to initially populate the HashMap

**Notes about work**
- Python microservice added as part of #245 
- This java should probably live in VroController but other places may be more suitable

**Comment by dianagriffin** [comment]
@ioarash cc/ @ENeal49 I've removed the "high priority" label from this ticket because iMVP features will not use the feature flags yet, but we DO want VRO to query the feature flag service for iMVP. 

So, this is **still internally a high priority** and should remain your top priority, @ioarash -- but it's not a blocking dependency for iMVP launch.

**Comment by yoomlam** [comment]
@ioarash 
> Upon app startup (probably after a few seconds delay), the app queries the service to initially populate the HashMap

The feature toggle microservice listens to a RabbitMQ queue, so VRO needs to add a message to that queue and use the response to populate the HashMap.

> The app will listen to Redis for changes to a Redis key.

VRO needs to subscribe to Redis to listen to the microservice's PUBLISH events.

See https://github.com/department-of-veterans-affairs/abd-vro/issues/245#issuecomment-1337639019
